In [1]:
# pip-Run the pip package manager within the current kernel.

In [2]:
pip install numpy

In [7]:
pip list #what all libraries you have?

Package             Version
------------------- ------------
astroid             2.3.3
attrs               19.3.0
backcall            0.1.0
beautifulsoup4      4.9.1
bleach              3.1.4
certifi             2019.11.28
chardet             3.0.4
click               7.1.2
colorama            0.4.3
cycler              0.10.0
decorator           4.4.2
defusedxml          0.6.0
entrypoints         0.3
gTTS                2.1.1
gTTS-token          1.1.3
h5py                2.10.0
idna                2.9
ipykernel           5.2.1
ipython             7.13.0
ipython-genutils    0.2.0
ipywidgets          7.5.1
isort               4.3.21
jedi                0.17.0Note: you may need to restart the kernel to use updated packages.

Jinja2              2.11.2
joblib              0.14.1
jsonschema          3.2.0
jupyter             1.0.0
jupyter-client      6.1.3
jupyter-console     6.1.0
jupyter-core        4.6.3
jupyterthemes       0.20.0
Keras               2.3.1
Keras-Applications  1.0.8
Keras

In [8]:
import numpy as np 


mccabe              0.6.1
mistune             0.8.4
nbconvert           5.6.1
nbformat            5.0.6
notebook            6.0.3
numpy               1.18.3
opencv-python       4.2.0.34
pandas              1.0.3
pandocfilters       1.4.2
parso               0.7.0
pep8                1.7.1
pickleshare         0.7.5
pip                 20.1.1
ply                 3.11
prometheus-client   0.7.1
prompt-toolkit      3.0.5
pygame              1.9.6
Pygments            2.6.1
pylint              2.4.4
pyparsing           2.4.7
pyrsistent          0.16.0
python-dateutil     2.8.1
pytz                2020.1
pywin32             227
pywinpty            0.5.7
PyYAML              5.3.1
pyzmq               19.0.0
qtconsole           4.7.3
QtPy                1.9.0
requests            2.23.0
scikit-learn        0.22.2.post1
scipy               1.4.1
Send2Trash          1.5.0
setuptools          41.2.0
six                 1.14.0
soupsieve           2.0.1
terminado           0.8.3
testpath            0.

In [95]:
l1=[1,2,3,4]

In [96]:
type(l1)

list

In [97]:
#creating arrays 
#we always have numpy array in NUMPY
arr=np.array(l1)

In [98]:
type(arr) #ndarray ==> n dimensional arrays

numpy.ndarray

In [99]:
arr

array([1, 2, 3, 4])

In [100]:
arr.shape #its a property not function
#it tells about how many elements are their

(4,)

In [20]:
arr.ndim

1

In [21]:
np.shape

<function numpy.shape(a)>

In [84]:
arr2=np.array([[1,2,3],
              [4,5,6],
              [8,9,"10"]])
# all the val will be converted to float when u change dtype of one!
print(arr2)

[['1' '2' '3']
 ['4' '5' '6']
 ['8' '9' '10']]


In [41]:
arr2.ndim

2

In [72]:
arr2=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]],dtype=float) #use shift+tab

In [73]:
arr2

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [74]:
arr2.ndim

2

In [75]:
arr2.shape

(3, 3)

In [76]:
arr2[2][2]

9.0

In [77]:
#you can see below example of 3D array
arr3=np.random.randint(1,20,size=(1,3,3)) 

In [78]:
arr3

array([[[15,  8,  8],
        [ 6, 12, 11],
        [ 4,  2,  4]]])

In [79]:
arr3=np.random.randint(1,20,size=(2,3,3))

In [80]:
arr3

array([[[ 8,  4,  9],
        [14,  4,  5],
        [14, 15,  5]],

       [[ 2, 18, 13],
        [ 4, 18,  7],
        [ 8,  3,  8]]])

In [85]:
arr2.dtype #data type 
#how many bit it takes to store integer

dtype('<U11')

In [86]:
l=range(10)
print(l)

range(1, 10)


In [83]:
[ i**2 for i in list(l)] #list comprehension

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [87]:
np.array(l)**2

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [89]:
import timeit
#we will get less time for numpy array

In [90]:
%timeit [ i**2 for i in list(l)]

22.4 µs ± 2.97 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [91]:
%timeit np.array(l)**2 #%timeit it only works in jupyter notebook

33.7 µs ± 6.17 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [101]:
arr


array([1, 2, 3, 4])

In [102]:
#all the elements are adde by 4
arr+4
#but in list we cant do operation like this 

array([5, 6, 7, 8])

In [104]:
arr*4

array([ 4,  8, 12, 16])

In [106]:
arr-4

array([-3, -2, -1,  0])

In [110]:
arr1=np.array([2,3,4,5])

In [111]:
arr1

array([2, 3, 4, 5])

In [112]:
arr1+arr2 #element wise addition

array([ 7,  9, 11, 13])

In [113]:
arr2=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]],dtype=float) #use shift+tab

In [114]:
arr2+2

array([[ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

## Random
(sub package)

In [121]:
np.random.randint(1,100)

72

In [119]:
arr1=np.random.randint(10,100,size=(5,5))
#size is basically size of array

In [116]:
arr2=np.random.randint(10,100,size=(5,5))

In [117]:
arr1

array([[38, 34, 89, 53, 68],
       [17, 26, 99, 49, 53],
       [55, 98, 93, 51, 82],
       [30, 10, 96, 21, 92],
       [95, 80, 92, 18, 30]])

In [122]:
arr2

array([[89, 89, 58, 93, 53],
       [66, 62, 94, 86, 80],
       [61, 93, 22, 66, 25],
       [91, 16, 17, 13, 54],
       [13, 72, 78, 49, 77]])

In [124]:
print(arr1[3,2]) #but we prefer this more
print(arr1[3][2])

18
18


# Operation on matrix

In [125]:
arr1+arr2

array([[125, 108, 135, 145, 126],
       [117, 119, 144, 182, 162],
       [ 87, 185,  44, 150,  90],
       [153, 108,  35,  44,  89],
       [ 98, 113, 107, 121,  99]])

In [127]:
#element wise multiplication
#not matrix multiplication
arr1*arr2

array([[3204, 1691, 4466, 4836, 3869],
       [3366, 3534, 4700, 8256, 6560],
       [1586, 8556,  484, 5544, 1625],
       [5642, 1472,  306,  403, 1890],
       [1105, 2952, 2262, 3528, 1694]])

In [128]:
arr1**2

array([[1296,  361, 5929, 2704, 5329],
       [2601, 3249, 2500, 9216, 6724],
       [ 676, 8464,  484, 7056, 4225],
       [3844, 8464,  324,  961, 1225],
       [7225, 1681,  841, 5184,  484]], dtype=int32)

In [133]:
arr1**arr2

array([[          0, -1309591245,  1389982985,           0, -1115847831],
       [ -909520087,  2008195665,           0,           0,           0],
       [          0,           0,   977272832,           0,   235062849],
       [          0,           0,  1695678464,  -505558625,  1833502425],
       [ 1851138725,  1719796289, -1320946887,           0,           0]],
      dtype=int32)

In [129]:
#matrix multiplication
np.dot(arr1,arr2)
#is same as
#arr1.dot(arr2) ==np.dot(arr1,arr2)

array([[14836, 17631, 12146, 14317, 13782],
       [21153, 20163, 17444, 18211, 20011],
       [18217, 16088, 17138, 16059, 18829],
       [15964, 15912, 15897, 16984, 15465],
       [18878, 15540, 12362, 15359, 14092]])

In [134]:
arr1.dot(arr2)

array([[14836, 17631, 12146, 14317, 13782],
       [21153, 20163, 17444, 18211, 20011],
       [18217, 16088, 17138, 16059, 18829],
       [15964, 15912, 15897, 16984, 15465],
       [18878, 15540, 12362, 15359, 14092]])

In [135]:
arr1.dot(arr2).dot(arr1).dot(arr2)
#you can try this also

array([[1303052305, 1254456601, 1093881801, 1183375433, 1201609076],
       [1726599257, 1660878556, 1444479231, 1566813663, 1587093642],
       [1534599560, 1469415883, 1283667819, 1390951166, 1409385767],
       [1426104935, 1368621384, 1205083436, 1299603134, 1318345833],
       [1345210034, 1308432982, 1130599231, 1229092908, 1240023033]])

In [131]:
#trying doing maatrix mul of three matrix
#we can first find dot b/w two then find dot b/w next two
#np.dot(np.dot(arr1,arr2),arr3)

# Array Slicing

In [136]:
arr1

array([[36, 19, 77, 52, 73],
       [51, 57, 50, 96, 82],
       [26, 92, 22, 84, 65],
       [62, 92, 18, 31, 35],
       [85, 41, 29, 72, 22]])

In [137]:
arr1[3,2]

18

In [138]:
arr1[3][2]

18

In [140]:
#arr[rows:cols]
arr1[1:4, 1:5]

array([[57, 50, 96, 82],
       [92, 22, 84, 65],
       [92, 18, 31, 35]])

In [141]:

arr1[:,1:3]

array([[19, 77],
       [57, 50],
       [92, 22],
       [92, 18],
       [41, 29]])

In [123]:
#imaages are just numpy array

In [125]:
#we can also Pass list of indexes
arr1[[1,3,4],:4]#if we want discontinoius things in ele


array([[10, 48, 35, 32],
       [14, 82, 51, 73],
       [86, 95, 13, 17]])

# Brodcasting

In [143]:
#broadcasting
arr1[:, :4]-arr1[1, :4] 
#so as we know we subtracted a 4,1 array from 5,4
#so it happens because of 4 is same in b/w 

array([[-15, -38,  27, -44],
       [  0,   0,   0,   0],
       [-25,  35, -28, -12],
       [ 11,  35, -32, -65],
       [ 34, -16, -21, -24]])

In [150]:

print(arr1[:, :4].shape)
arr1[:, :4]

(5, 4)


array([[36, 19, 77, 52],
       [51, 57, 50, 96],
       [26, 92, 22, 84],
       [62, 92, 18, 31],
       [85, 41, 29, 72]])

In [151]:
 
print(arr1[1, :4].shape)
arr1[1, :4]

(4,)


array([51, 57, 50, 96])

In [130]:
np.array([[1,2,3],
         [4,5,6],
         [7,8,9]])+ np.array([1,2,3])

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [131]:
np.array([[1,2,3],[4,5,6],[7,8,9]])+ np.array([1,2,3])

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [152]:
np.array([[1,2,3],[4,5,6],[7,8,9]])+ np.array([1,2,3,4])

ValueError: operands could not be broadcast together with shapes (3,3) (4,) 

In [153]:
np.zeros((5,))

array([0., 0., 0., 0., 0.])

In [154]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [155]:
np.full((5,4), fill_value=99) #it will fillvalues 

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])

In [161]:
np.diag((4,4),)
#read documentation and see examples

array([[4, 0],
       [0, 4]])

In [163]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [164]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [168]:
np.array(range(33,100,2))

array([33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65,
       67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [169]:
#in numpy we have func called 
#arange
np.arange(33,100,2)

array([33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65,
       67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [171]:
#Return evenly spaced numbers over a specified interval.
np.linspace(start=1,stop=2,num=50)


array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

#### read Documentation