# Numpy - for mathematical operations

In [19]:
# pip-Run the pip package manager within the current kernel.

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [21]:
pip list #what all libraries you have?

Package                            Version
---------------------------------- -------------------
-                                  ipy
-.ipy                              1.5.0
-0ipy                              1.5.0
-cipy                              1.5.0
-ipy                               1.5.0
absl-py                            0.10.0
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 1.9.12
anaconda-project                   0.8.3
argh                               0.26.2
asn1crypto                         1.3.0
astroid                            2.4.2
astropy                            4.0.1.post1
astunparse                         1.6.3
atomicwrites                       1.4.0
attrs                              19.3.0
autopep8                           1.5.3
Babel                              2.8.0
backcall                           0.2.0
backports.functools-lru-cache      1.6.1
backports.shutil-get-terminal-si

In [3]:
import numpy as np 

In [4]:
l1=[1,2,3,4]

In [5]:
type(l1)

list

### creating arrays 


In [6]:
#we always have numpy array in NUMPY
arr=np.array(l1)

In [7]:
type(arr) #ndarray ==> n dimensional arrays

numpy.ndarray

In [8]:
arr

array([1, 2, 3, 4])

In [9]:
arr.shape #its a property not function
#it tells about how many elements are their
#(4,) is linear while (4,1) is a 2D array 

(4,)

In [39]:
arr.ndim # so 1D array

1

In [40]:
np.shape

<function numpy.shape(a)>

In [35]:
arr2=np.array([[1,2.2,3],
              [4,5,6],
              [8,9,"10"]],dtype=int)
# all the val will be converted to float when u change dtype of one!
print(arr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]


In [36]:
arr2.ndim #its a 2D array

2

In [37]:
arr2=np.array([[1,2.3,3],
              [4,5,6],
              [7,8,9]],dtype=float) #use shift+tab

In [18]:
arr2

array([[1. , 2.3, 3. ],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]])

In [19]:
arr2.ndim

2

In [20]:
arr2.shape

(3, 3)

In [21]:
arr2[2][2]

9.0

In [22]:
#you can see below example of 3D array
arr3=np.random.randint(1,20,size=(1,3,3)) 

In [23]:
arr3

array([[[ 6,  3, 19],
        [18, 11,  6],
        [19,  9, 13]]])

In [24]:
arr3=np.random.randint(1,20,size=(2,3,3))

In [25]:
arr3

array([[[12, 19,  8],
        [15, 15,  7],
        [14,  8, 10]],

       [[ 2, 15, 15],
        [ 9, 10,  3],
        [10, 18, 10]]])

### Datatypes

In [26]:

arr2.dtype #data type 
#how many bit it takes to store integer

dtype('float64')

In [27]:
l=range(10)
print(l)

range(0, 10)


In [28]:
[ i**2 for i in list(l)] #list comprehension

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [45]:
np.array(l)**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [46]:
import timeit
#we will get less time for numpy array

In [47]:
%timeit [ i**2 for i in list(l)]

2.29 µs ± 107 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [48]:
%timeit np.array(l)**2 #%timeit it only works in jupyter notebook

5.19 µs ± 356 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [49]:
arr


array([1, 2, 3, 4])

In [50]:
#all the elements are adde by 4
arr+4
#but in list we cant do operation like this 

array([5, 6, 7, 8])

In [104]:
arr*4

array([ 4,  8, 12, 16])

In [106]:
arr-4

array([-3, -2, -1,  0])

In [110]:
arr1=np.array([2,3,4,5])

In [111]:
arr1

array([2, 3, 4, 5])

In [112]:
arr1+arr2 #element wise addition

array([ 7,  9, 11, 13])

In [113]:
arr2=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]],dtype=float) #use shift+tab

In [114]:
arr2+2

array([[ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

## Random
(sub package)

In [59]:
np.random.randint(1,100)

21

In [60]:
arr1=np.random.randint(10,100,size=(5,5))
#size is basically size of array

In [61]:
arr2=np.random.randint(10,100,size=(5,5))

In [62]:
arr1

array([[47, 67, 10, 39, 11],
       [48, 22, 47, 48, 58],
       [14, 31, 28, 34, 93],
       [80, 78, 52, 61, 94],
       [26, 74, 85, 39, 35]])

In [63]:
arr2

array([[57, 76, 68, 64, 84],
       [26, 56, 72, 66, 94],
       [57, 24, 51, 56, 76],
       [22, 31, 17, 75, 32],
       [98, 33, 20, 33, 18]])

In [64]:
print(arr1[3,2]) #but we prefer this more
print(arr1[3][2])

52
52


### Numpy Random Module
- rand : Random values in a given shape.
- randn : Return a sample (or samples) from the “standard normal” distribution.
- randint : Return random integers from low (inclusive) to high (exclusive).
- random : Return random floats in the half-open interval [0.0, 1.0)
- choice : Generates a random sample from a given 1-D array
- Shuffle : Shuffles the contents of a sequence

In [1]:
import numpy as np
a = np.arange(10) + 5
# Return evenly spaced values within a given interval.
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [8]:
np.random.shuffle(a)
print(a)
#all the element of a are randomly shuffled #everytime

[7 8 6]


In [9]:
#Return values from Standard Normal Ditributions
a=np.random.rand(2,3)
print(a)

[[0.90068143 0.80358463 0.55563024]
 [0.59029825 0.5992269  0.95534435]]


In [14]:
np.random.seed(1) #everytime you want random no. to be genrated same you have set aseed value
# if you dont want to use Pseudo random no. generation
# you can replicate result by using seed(store the state of random number)
a=np.random.randint(5,10,3)
print(a)
# three no. which are from these range

[8 9 5]


# Operation on matrix

In [65]:
arr1+arr2

array([[104, 143,  78, 103,  95],
       [ 74,  78, 119, 114, 152],
       [ 71,  55,  79,  90, 169],
       [102, 109,  69, 136, 126],
       [124, 107, 105,  72,  53]])

In [66]:
np.add(arr1,arr2)

array([[104, 143,  78, 103,  95],
       [ 74,  78, 119, 114, 152],
       [ 71,  55,  79,  90, 169],
       [102, 109,  69, 136, 126],
       [124, 107, 105,  72,  53]])

In [67]:
#element wise multiplication
#not matrix multiplication
arr1*arr2

array([[2679, 5092,  680, 2496,  924],
       [1248, 1232, 3384, 3168, 5452],
       [ 798,  744, 1428, 1904, 7068],
       [1760, 2418,  884, 4575, 3008],
       [2548, 2442, 1700, 1287,  630]])

In [68]:
np.multiply(arr1,arr2)

array([[2679, 5092,  680, 2496,  924],
       [1248, 1232, 3384, 3168, 5452],
       [ 798,  744, 1428, 1904, 7068],
       [1760, 2418,  884, 4575, 3008],
       [2548, 2442, 1700, 1287,  630]])

In [71]:
print(np.divide(arr1,arr2))
print("-----------------------------------------------------------")
print(arr1/arr2)

[[0.8245614  0.88157895 0.14705882 0.609375   0.13095238]
 [1.84615385 0.39285714 0.65277778 0.72727273 0.61702128]
 [0.24561404 1.29166667 0.54901961 0.60714286 1.22368421]
 [3.63636364 2.51612903 3.05882353 0.81333333 2.9375    ]
 [0.26530612 2.24242424 4.25       1.18181818 1.94444444]]
-----------------------------------------------------------
[[0.8245614  0.88157895 0.14705882 0.609375   0.13095238]
 [1.84615385 0.39285714 0.65277778 0.72727273 0.61702128]
 [0.24561404 1.29166667 0.54901961 0.60714286 1.22368421]
 [3.63636364 2.51612903 3.05882353 0.81333333 2.9375    ]
 [0.26530612 2.24242424 4.25       1.18181818 1.94444444]]


In [75]:
np.sqrt(arr1)

array([[6.8556546 , 8.18535277, 3.16227766, 6.244998  , 3.31662479],
       [6.92820323, 4.69041576, 6.8556546 , 6.92820323, 7.61577311],
       [3.74165739, 5.56776436, 5.29150262, 5.83095189, 9.64365076],
       [8.94427191, 8.83176087, 7.21110255, 7.81024968, 9.69535971],
       [5.09901951, 8.60232527, 9.21954446, 6.244998  , 5.91607978]])

In [76]:
arr1**2

array([[2209, 4489,  100, 1521,  121],
       [2304,  484, 2209, 2304, 3364],
       [ 196,  961,  784, 1156, 8649],
       [6400, 6084, 2704, 3721, 8836],
       [ 676, 5476, 7225, 1521, 1225]], dtype=int32)

In [77]:
arr1**arr2

array([[  627453615, -1631139343,           0,  1448128001,   321008369],
       [          0,           0, -1605546367,           0,           0],
       [          0, -2077209343,           0,           0,  -232775823],
       [          0, -2147483648,           0,    56577477,           0],
       [          0,           0,  1743204721,   857325863,   -81531895]],
      dtype=int32)

In [80]:
#matrix multiplication / DOT PRODUCT

np.dot(arr1,arr2)
#is same as
#arr1.dot(arr2) ==np.dot(arr1,arr2)

array([[ 6927,  9136,  9413, 11278, 12452],
       [12727,  9410,  9221, 12670, 12252],
       [13062,  7595,  7050, 10129,  8980],
       [20106, 16689, 16625, 20857, 21648],
       [12539, 10524, 12794, 15388, 17478]])

### Dot product along axis

In [87]:
# multiplication of vectors will give you a scalar

a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(a.dot(b))
print(sum(a))
print(np.sum(a,axis=0)) #sum along column 
#=====> axis=0

""" axis =1 sum along rows 
^
|
|
|

"""


30
10
10


' axis =1\n^\n|\n|\n|\n\n'

In [79]:
arr1.dot(arr2)

array([[ 6927,  9136,  9413, 11278, 12452],
       [12727,  9410,  9221, 12670, 12252],
       [13062,  7595,  7050, 10129,  8980],
       [20106, 16689, 16625, 20857, 21648],
       [12539, 10524, 12794, 15388, 17478]])

In [135]:
arr1.dot(arr2).dot(arr1).dot(arr2)
#you can try this also

array([[1303052305, 1254456601, 1093881801, 1183375433, 1201609076],
       [1726599257, 1660878556, 1444479231, 1566813663, 1587093642],
       [1534599560, 1469415883, 1283667819, 1390951166, 1409385767],
       [1426104935, 1368621384, 1205083436, 1299603134, 1318345833],
       [1345210034, 1308432982, 1130599231, 1229092908, 1240023033]])

In [131]:
#trying doing maatrix mul of three matrix
#we can first find dot b/w two then find dot b/w next two
#np.dot(np.dot(arr1,arr2),arr3)

# Array Slicing

In [136]:
arr1

array([[36, 19, 77, 52, 73],
       [51, 57, 50, 96, 82],
       [26, 92, 22, 84, 65],
       [62, 92, 18, 31, 35],
       [85, 41, 29, 72, 22]])

In [137]:
arr1[3,2]

18

In [138]:
arr1[3][2]

18

In [140]:
#arr[rows:cols]
arr1[1:4, 1:5]

array([[57, 50, 96, 82],
       [92, 22, 84, 65],
       [92, 18, 31, 35]])

In [141]:

arr1[:,1:3]

array([[19, 77],
       [57, 50],
       [92, 22],
       [92, 18],
       [41, 29]])

In [123]:
#imaages are just numpy array

In [125]:
#we can also Pass list of indexes
arr1[[1,3,4],:4]#if we want discontinoius things in ele


array([[10, 48, 35, 32],
       [14, 82, 51, 73],
       [86, 95, 13, 17]])

### Stacking of arrays

In [91]:
a=np.random.randint(10,100,size=(4,))
b=np.random.randint(10,100,size=(4,))
print(a)
print(b)

[69 46 95 80]
[14 71 34 82]


In [93]:
np.stack((a,b),axis=1)

array([[69, 14],
       [46, 71],
       [95, 34],
       [80, 82]])

In [102]:
np.vstack(a)

array([[69],
       [46],
       [95],
       [80]])

In [106]:
c=np.random.randint(10,100,size=(2,2))
d=np.random.randint(10,100,size=(2,2))
print(c)
print("another numpy array:")
print(d)

[[96 62]
 [57 80]]
another numpy array:
[[39 76]
 [61 90]]


In [107]:
np.stack((c,d),axis=0) #along columns

array([[[96, 62],
        [57, 80]],

       [[39, 76],
        [61, 90]]])

In [109]:
np.stack((c,d),axis=1) #along rows 

array([[[96, 62],
        [39, 76]],

       [[57, 80],
        [61, 90]]])

In [113]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])

print(a)
b=b**2
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [114]:
#it can only stack along column 
np.stack((a,b),axis=0)

array([[ 1,  2,  3,  4],
       [ 1,  4,  9, 16]])

# Brodcasting

In [143]:
#broadcasting
arr1[:, :4]-arr1[1, :4] 
#so as we know we subtracted a 4,1 array from 5,4
#so it happens because of 4 is same in b/w 

array([[-15, -38,  27, -44],
       [  0,   0,   0,   0],
       [-25,  35, -28, -12],
       [ 11,  35, -32, -65],
       [ 34, -16, -21, -24]])

In [150]:

print(arr1[:, :4].shape)
arr1[:, :4]

(5, 4)


array([[36, 19, 77, 52],
       [51, 57, 50, 96],
       [26, 92, 22, 84],
       [62, 92, 18, 31],
       [85, 41, 29, 72]])

In [151]:
 
print(arr1[1, :4].shape)
arr1[1, :4]

(4,)


array([51, 57, 50, 96])

In [130]:
np.array([[1,2,3],
         [4,5,6],
         [7,8,9]])+ np.array([1,2,3])

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [131]:
np.array([[1,2,3],[4,5,6],[7,8,9]])+ np.array([1,2,3])

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [152]:
np.array([[1,2,3],[4,5,6],[7,8,9]])+ np.array([1,2,3,4])

ValueError: operands could not be broadcast together with shapes (3,3) (4,) 

### Create Zeros , Ones ,Custom array

In [41]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [42]:
np.zeros((5,))

array([0., 0., 0., 0., 0.])

In [43]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [46]:
#array of some constant 
c= np.full((4,5),2)
print(c)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [47]:
#Identiy Matrix-Size/Square matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
#how to add specific elements to random matrix
rm=np.random.random((2,3))
rm[1,1:3]=1
print(rm)



[[0.24593359 0.12350462 0.27235353]
 [0.93650972 1.         1.        ]]


In [58]:
#set some rows and columns with any values
#slicing
z=np.zeros((3,3))
print(z)
print("changed:")
z[1,:]=5
z[:,-1]=7
print(z)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
changed:
[[0. 0. 7.]
 [5. 5. 7.]
 [0. 0. 7.]]


In [155]:
np.full((5,4), fill_value=99) #it will fillvalues 

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])

In [48]:
np.diag((4,4),)
#read documentation and see examples

array([[4, 0],
       [0, 4]])

In [49]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [50]:
np.array(range(33,100,2))

array([33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65,
       67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [51]:
#in numpy we have func called 
#arange
np.arange(33,100,2)

array([33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65,
       67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [52]:
#Return evenly spaced numbers over a specified interval.
np.linspace(start=1,stop=2,num=100)


array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
       1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
       1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
       1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
       1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
       1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
       1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
       1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
       1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
       1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
       1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
       1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
       1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
       1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
       1.70707071, 1.71717172, 1.72727273, 1.73737374, 1.74747

#### read Documentation