# Functions in Numpy

In [3]:
import numpy as np

In [4]:
arr=np.random.randint(10,100,size=(5,4))

In [5]:
arr

array([[84, 64, 46, 38],
       [47, 66, 91, 40],
       [29, 21, 96, 30],
       [22, 85, 32, 53],
       [72, 39, 16, 47]])

In [6]:
np.sum(arr)

1018

In [7]:
np.mean(arr)

50.9

In [8]:
np.sum(arr[:,:1])

254

In [9]:
np.sum(arr,axis=0)#axis 0 means row
#colwise sum

array([254, 275, 281, 208])

In [10]:
np.sum(arr,axis=1)#axis 1 means col
#row wise sum
#if u take sum across a 4 ele or 1 axis then u get 5 or 0 axis no of ele

array([232, 244, 176, 192, 174])

In [14]:
arr1=np.random.randint(1,100,size=30)

In [17]:
arr1


array([60,  8, 78, 83, 59, 55,  6, 48, 69, 91, 79, 31, 26, 84, 98, 94, 88,
       64, 39, 33, 11, 22, 91, 88, 44, 38, 46, 83, 11, 81])

In [18]:
arr1.shape

(30,)

In [33]:
arr_3d=np.random.randint(1,10,size=(3,2,4))

In [34]:
arr_3d

array([[[5, 8, 9, 1],
        [7, 7, 7, 9]],

       [[5, 1, 5, 8],
        [2, 7, 9, 8]],

       [[9, 8, 1, 5],
        [7, 3, 6, 4]]])

In [35]:
arr_3d.shape

(3, 2, 4)

In [36]:
np.sum(arr_3d,axis=0)
#0 here is 3 so ans would come in(2,4)

array([[19, 17, 15, 14],
       [16, 17, 22, 21]])

In [38]:
np.sum(arr_3d,axis=1)
#1 here is 2 so ans would come in(3,4)

array([[12, 15, 16, 10],
       [ 7,  8, 14, 16],
       [16, 11,  7,  9]])

In [39]:
np.sum(arr_3d,axis=-1)
#-1 or 2 here is 4 so ans would come in(3,2)
#here we can too place 2 instead of -1

array([[23, 30],
       [19, 26],
       [23, 20]])

### Masking

In [42]:
arr>50

array([[ True,  True, False, False],
       [False,  True,  True, False],
       [False, False,  True, False],
       [False,  True, False,  True],
       [ True, False, False, False]])

In [44]:
arr[0,0]>50

True

In [46]:
new_arr=np.random.randint(1,100,size=30)

In [48]:
new_arr

array([81, 96, 70, 83, 65, 69, 88, 57, 26, 14, 46, 69,  7, 94,  5, 43, 15,
       76,  7, 82, 39, 40, 80, 83, 15, 65,  2, 99, 90, 78])

In [50]:
#Masking
new_arr>50

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False,  True, False,  True, False, False, False,  True,
       False,  True, False, False,  True,  True, False,  True, False,
        True,  True,  True])

In [51]:
new_arr[[0,1,-1]]

array([81, 96, 78])

In [52]:
mask=new_arr>50
mask

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False,  True, False,  True, False, False, False,  True,
       False,  True, False, False,  True,  True, False,  True, False,
        True,  True,  True])

In [54]:
new_arr[mask]

array([81, 96, 70, 83, 65, 69, 88, 57, 69, 94, 76, 82, 80, 83, 65, 99, 90,
       78])

In [55]:
new_arr[new_arr>50]

array([81, 96, 70, 83, 65, 69, 88, 57, 69, 94, 76, 82, 80, 83, 65, 99, 90,
       78])

In [56]:
new_arr[new_arr%2==0]

array([96, 70, 88, 26, 14, 46, 94, 76, 82, 40, 80,  2, 90, 78])

In [57]:
arr[:2,:2]=999

In [61]:
arr

array([[999, 999,  46,  38],
       [999, 999,  91,  40],
       [ 29,  21,  96,  30],
       [ 22,  85,  32,  53],
       [ 72,  39,  16,  47]])

In [62]:
np.min(arr1)

6

In [66]:
np.max(arr1)

98

In [76]:
arr1=np.random.randint(1,10,size=(3,3))

In [91]:
# np.max(arr1,axis=0) #check for 2d array
arr1

array([[6, 2, 9],
       [6, 5, 5],
       [7, 3, 4]])

In [93]:
new_arr

array([81, 96, 70, 83, 65, 69, 88, 57, 26, 14, 46, 69,  7, 94,  5, 43, 15,
       76,  7, 82, 39, 40, 80, 83, 15, 65,  2, 99, 90, 78])

In [78]:
#2D and 3D aray not work 
#it will just work on simple vector
#for more thean one dimension we can find mi/max
#of one then min/max of them
np.min(arr1,axis=0)
#colwise min val
#first axis

array([6, 2, 4])

In [80]:
np.max(arr1,axis=1)
#row wise max val
#second axis

array([9, 6, 7])

In [81]:
new_arr.min()

2

In [84]:
new_arr.max()

99

In [88]:
print(new_arr[27]) #u can put val and check
new_arr.argmax()
#it will give index of max ele

99


27

In [90]:
print(new_arr[26])
new_arr.argmin()
#it will give index of min ele

2


26

### Reshape

In [94]:
arr

array([[999, 999,  46,  38],
       [999, 999,  91,  40],
       [ 29,  21,  96,  30],
       [ 22,  85,  32,  53],
       [ 72,  39,  16,  47]])

In [95]:
#reshape
arr.shape

(5, 4)

In [100]:
np.reshape(arr,newshape=(2,10))
#see in DoC newshape take tuple or int(vector)
#but array can variate b/w vector only (20,) and (,20)
# as 5x4= 20 total no. of ele is same throughout

array([[999, 999,  46,  38, 999, 999,  91,  40,  29,  21],
       [ 96,  30,  22,  85,  32,  53,  72,  39,  16,  47]])

In [104]:
np.reshape(arr,newshape=(-1,10))
#so -1 here automatically intialize itself it can be any side

array([[999, 999,  46,  38, 999, 999,  91,  40,  29,  21],
       [ 96,  30,  22,  85,  32,  53,  72,  39,  16,  47]])

In [106]:
a=np.arange(1,10)

In [107]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
b=a

In [109]:
a[:5]=999

In [110]:
a

array([999, 999, 999, 999, 999,   6,   7,   8,   9])

In [111]:
b#this happens dur to referncing

array([999, 999, 999, 999, 999,   6,   7,   8,   9])

In [114]:
b=a.copy() # now changes arenot reflected

## Vectorization

In [119]:
a=np.array([2,3])
b=np.array([5,4])

In [120]:
b[0]

5

In [121]:
def distance(a,b):
    dx=b[0]-a[0]
    dy=b[1]-a[1]
    
    return np.sqrt(dx**2+dy**2)

In [122]:
distance(a,b)

3.1622776601683795

In [123]:
np.sqrt(10**0.5)

1.7782794100389228

In [69]:
np.sum((b-a)**2)**0.5

3.1622776601683795

In [70]:
#ranspose of array
np.transpose(arr)

array([[39, 25, 59, 79, 71],
       [36, 12, 85, 31, 14],
       [42, 18, 72, 80, 28],
       [54, 44, 30, 30, 74]])

In [124]:
#or 
arr.T

array([[999, 999,  29,  22,  72],
       [999, 999,  21,  85,  39],
       [ 46,  91,  96,  32,  16],
       [ 38,  40,  30,  53,  47]])

In [ ]:
#np.linalg.inv(arr)
#to invrese

In [72]:
dir(np) #np. +shift+tab

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_

In [74]:
np.sin(90)

0.8939966636005579