In [19]:
# pip-Run the pip package manager within the current kernel.

In [20]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [21]:
pip list #what all libraries you have?

Package                            Version
---------------------------------- -------------------
-                                  ipy
-.ipy                              1.5.0
-0ipy                              1.5.0
-cipy                              1.5.0
-ipy                               1.5.0
absl-py                            0.10.0
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 1.9.12
anaconda-project                   0.8.3
argh                               0.26.2
asn1crypto                         1.3.0
astroid                            2.4.2
astropy                            4.0.1.post1
astunparse                         1.6.3
atomicwrites                       1.4.0
attrs                              19.3.0
autopep8                           1.5.3
Babel                              2.8.0
backcall                           0.2.0
backports.functools-lru-cache      1.6.1
backports.shutil-get-terminal-si

In [22]:
import numpy as np 

In [23]:
l1=[1,2,3,4]

In [24]:
type(l1)

list

In [25]:
#creating arrays 
#we always have numpy array in NUMPY
arr=np.array(l1)

In [26]:
type(arr) #ndarray ==> n dimensional arrays

numpy.ndarray

In [27]:
arr

array([1, 2, 3, 4])

In [28]:
arr.shape #its a property not function
#it tells about how many elements are their

(4,)

In [29]:
arr.ndim

1

In [30]:
np.shape

<function numpy.shape(a)>

In [51]:
arr2=np.array([[1,2.2,3],
              [4,5,6],
              [8,9,"10"]],dtype=int)
# all the val will be converted to float when u change dtype of one!
print(arr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]


In [52]:
arr2.ndim

2

In [53]:
arr2=np.array([[1,2.3,3],
              [4,5,6],
              [7,8,9]],dtype=float) #use shift+tab

In [34]:
arr2

array([[1. , 2.3, 3. ],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]])

In [35]:
arr2.ndim

2

In [36]:
arr2.shape

(3, 3)

In [37]:
arr2[2][2]

9.0

In [38]:
#you can see below example of 3D array
arr3=np.random.randint(1,20,size=(1,3,3)) 

In [39]:
arr3

array([[[13, 11, 18],
        [16,  5, 12],
        [15, 15, 10]]])

In [40]:
arr3=np.random.randint(1,20,size=(2,3,3))

In [41]:
arr3

array([[[ 6, 16, 15],
        [10,  3,  7],
        [18, 19,  1]],

       [[15,  1, 19],
        [17,  5, 12],
        [17,  9,  9]]])

In [42]:
arr2.dtype #data type 
#how many bit it takes to store integer

dtype('float64')

In [43]:
l=range(10)
print(l)

range(0, 10)


In [44]:
[ i**2 for i in list(l)] #list comprehension

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [45]:
np.array(l)**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [46]:
import timeit
#we will get less time for numpy array

In [47]:
%timeit [ i**2 for i in list(l)]

2.29 µs ± 107 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [48]:
%timeit np.array(l)**2 #%timeit it only works in jupyter notebook

5.19 µs ± 356 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [49]:
arr


array([1, 2, 3, 4])

In [50]:
#all the elements are adde by 4
arr+4
#but in list we cant do operation like this 

array([5, 6, 7, 8])

In [104]:
arr*4

array([ 4,  8, 12, 16])

In [106]:
arr-4

array([-3, -2, -1,  0])

In [110]:
arr1=np.array([2,3,4,5])

In [111]:
arr1

array([2, 3, 4, 5])

In [112]:
arr1+arr2 #element wise addition

array([ 7,  9, 11, 13])

In [113]:
arr2=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]],dtype=float) #use shift+tab

In [114]:
arr2+2

array([[ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

## Random
(sub package)

In [121]:
np.random.randint(1,100)

72

In [119]:
arr1=np.random.randint(10,100,size=(5,5))
#size is basically size of array

In [116]:
arr2=np.random.randint(10,100,size=(5,5))

In [117]:
arr1

array([[38, 34, 89, 53, 68],
       [17, 26, 99, 49, 53],
       [55, 98, 93, 51, 82],
       [30, 10, 96, 21, 92],
       [95, 80, 92, 18, 30]])

In [122]:
arr2

array([[89, 89, 58, 93, 53],
       [66, 62, 94, 86, 80],
       [61, 93, 22, 66, 25],
       [91, 16, 17, 13, 54],
       [13, 72, 78, 49, 77]])

In [124]:
print(arr1[3,2]) #but we prefer this more
print(arr1[3][2])

18
18


# Operation on matrix

In [125]:
arr1+arr2

array([[125, 108, 135, 145, 126],
       [117, 119, 144, 182, 162],
       [ 87, 185,  44, 150,  90],
       [153, 108,  35,  44,  89],
       [ 98, 113, 107, 121,  99]])

In [127]:
#element wise multiplication
#not matrix multiplication
arr1*arr2

array([[3204, 1691, 4466, 4836, 3869],
       [3366, 3534, 4700, 8256, 6560],
       [1586, 8556,  484, 5544, 1625],
       [5642, 1472,  306,  403, 1890],
       [1105, 2952, 2262, 3528, 1694]])

In [128]:
arr1**2

array([[1296,  361, 5929, 2704, 5329],
       [2601, 3249, 2500, 9216, 6724],
       [ 676, 8464,  484, 7056, 4225],
       [3844, 8464,  324,  961, 1225],
       [7225, 1681,  841, 5184,  484]], dtype=int32)

In [133]:
arr1**arr2

array([[          0, -1309591245,  1389982985,           0, -1115847831],
       [ -909520087,  2008195665,           0,           0,           0],
       [          0,           0,   977272832,           0,   235062849],
       [          0,           0,  1695678464,  -505558625,  1833502425],
       [ 1851138725,  1719796289, -1320946887,           0,           0]],
      dtype=int32)

In [129]:
#matrix multiplication
np.dot(arr1,arr2)
#is same as
#arr1.dot(arr2) ==np.dot(arr1,arr2)

array([[14836, 17631, 12146, 14317, 13782],
       [21153, 20163, 17444, 18211, 20011],
       [18217, 16088, 17138, 16059, 18829],
       [15964, 15912, 15897, 16984, 15465],
       [18878, 15540, 12362, 15359, 14092]])

In [134]:
arr1.dot(arr2)

array([[14836, 17631, 12146, 14317, 13782],
       [21153, 20163, 17444, 18211, 20011],
       [18217, 16088, 17138, 16059, 18829],
       [15964, 15912, 15897, 16984, 15465],
       [18878, 15540, 12362, 15359, 14092]])

In [135]:
arr1.dot(arr2).dot(arr1).dot(arr2)
#you can try this also

array([[1303052305, 1254456601, 1093881801, 1183375433, 1201609076],
       [1726599257, 1660878556, 1444479231, 1566813663, 1587093642],
       [1534599560, 1469415883, 1283667819, 1390951166, 1409385767],
       [1426104935, 1368621384, 1205083436, 1299603134, 1318345833],
       [1345210034, 1308432982, 1130599231, 1229092908, 1240023033]])

In [131]:
#trying doing maatrix mul of three matrix
#we can first find dot b/w two then find dot b/w next two
#np.dot(np.dot(arr1,arr2),arr3)

# Array Slicing

In [136]:
arr1

array([[36, 19, 77, 52, 73],
       [51, 57, 50, 96, 82],
       [26, 92, 22, 84, 65],
       [62, 92, 18, 31, 35],
       [85, 41, 29, 72, 22]])

In [137]:
arr1[3,2]

18

In [138]:
arr1[3][2]

18

In [140]:
#arr[rows:cols]
arr1[1:4, 1:5]

array([[57, 50, 96, 82],
       [92, 22, 84, 65],
       [92, 18, 31, 35]])

In [141]:

arr1[:,1:3]

array([[19, 77],
       [57, 50],
       [92, 22],
       [92, 18],
       [41, 29]])

In [123]:
#imaages are just numpy array

In [125]:
#we can also Pass list of indexes
arr1[[1,3,4],:4]#if we want discontinoius things in ele


array([[10, 48, 35, 32],
       [14, 82, 51, 73],
       [86, 95, 13, 17]])

# Brodcasting

In [143]:
#broadcasting
arr1[:, :4]-arr1[1, :4] 
#so as we know we subtracted a 4,1 array from 5,4
#so it happens because of 4 is same in b/w 

array([[-15, -38,  27, -44],
       [  0,   0,   0,   0],
       [-25,  35, -28, -12],
       [ 11,  35, -32, -65],
       [ 34, -16, -21, -24]])

In [150]:

print(arr1[:, :4].shape)
arr1[:, :4]

(5, 4)


array([[36, 19, 77, 52],
       [51, 57, 50, 96],
       [26, 92, 22, 84],
       [62, 92, 18, 31],
       [85, 41, 29, 72]])

In [151]:
 
print(arr1[1, :4].shape)
arr1[1, :4]

(4,)


array([51, 57, 50, 96])

In [130]:
np.array([[1,2,3],
         [4,5,6],
         [7,8,9]])+ np.array([1,2,3])

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [131]:
np.array([[1,2,3],[4,5,6],[7,8,9]])+ np.array([1,2,3])

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [152]:
np.array([[1,2,3],[4,5,6],[7,8,9]])+ np.array([1,2,3,4])

ValueError: operands could not be broadcast together with shapes (3,3) (4,) 

In [153]:
np.zeros((5,))

array([0., 0., 0., 0., 0.])

In [154]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [155]:
np.full((5,4), fill_value=99) #it will fillvalues 

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])

In [161]:
np.diag((4,4),)
#read documentation and see examples

array([[4, 0],
       [0, 4]])

In [163]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [164]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [168]:
np.array(range(33,100,2))

array([33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65,
       67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [169]:
#in numpy we have func called 
#arange
np.arange(33,100,2)

array([33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65,
       67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [56]:
#Return evenly spaced numbers over a specified interval.
np.linspace(start=1,stop=2,num=100)


array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
       1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
       1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
       1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
       1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
       1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
       1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
       1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
       1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
       1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
       1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
       1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
       1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
       1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
       1.70707071, 1.71717172, 1.72727273, 1.73737374, 1.74747

#### read Documentation