In [2]:
import torch

print(torch.__version__)

1.8.1


In [3]:
torch.get_default_dtype()

torch.float32

In [4]:
torch.set_default_dtype(torch.int) 
#only floating pt is supporeted

TypeError: only floating-point types are supported as the default type

In [5]:
torch.set_default_dtype(torch.float64) 


In [6]:
torch.get_default_dtype()

torch.float64

In [7]:
#2d Tensor
arr=torch.Tensor([[1,2,3],[4,5,6]])
print(arr)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [8]:
torch.is_tensor(arr) #object initaited is of type tensor ?

True

In [9]:
torch.numel(arr)
#it has total 6 element

6

In [11]:
#how to create a unintailised tensor (just declare shape only)
unintialised_tensor = torch.Tensor(2,2)
print(unintialised_tensor)
#result tensor object is unitailised

tensor([[ 1.0054e-47,  3.5067e-33],
        [3.9991e+252,  5.3994e-66]])


In [12]:
#Randomly allocating Tensors
randarr=torch.rand(2,2)
print(randarr)
#its a good way to intialise your model parameter

tensor([[0.4471, 0.7622],
        [0.5865, 0.6820]])


In [13]:
tensor_int= torch.tensor([5,3]).type(torch.IntTensor)


In [14]:
tensor_int #integer tensor on GPU #torch.cuda for GPU

tensor([5, 3], dtype=torch.int32)

In [18]:
tensor_short =torch.ShortTensor([1.0,2.0,3.0])
print(tensor_short) #tensor of 16 bit integer

tensor([1, 2, 3], dtype=torch.int16)


<ipython-input-18-a08be9521125>:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  tensor_short =torch.ShortTensor([1.0,2.0,3.0])


In [20]:
#for taking half memeory than usaul that is 32 bit
tensor_half = torch.tensor([1.0,2.0,3.0]).type(torch.half)
print(tensor_half)

tensor([1., 2., 3.], dtype=torch.float16)


In [21]:
tensor_fill = torch.full((2,6) , fill_value = 10)
tensor_fill

tensor([[10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10]])

In [22]:
tensor_ones = torch.ones([2,4] , dtype = torch.int32)
print(tensor_ones)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)


In [24]:
# if you want to use same size of zeroes us this syntax (like word)

tensor_zeroes = torch.zeros_like(tensor_ones)
print(tensor_zeroes)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)


In [26]:
#it will create 2 D matrix main diagonal filled with ones 
tensor_eye = torch.eye(5) # 5 rows and columns
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [28]:
nonzero = torch.nonzero(tensor_eye)
nonzero # it tell at which postion non zeroth element lie  in our tensor

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [ ]:
#copy of an tensor ,numpy arry ,list 
