# KNN using Sklearn

In [45]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

In [46]:
knn = KNeighborsClassifier() #creating object 

### Data Preprocessing

In [47]:
x=pd.read_csv("../Datasets/xdata.csv").values
y=pd.read_csv("../Datasets/ydata.csv").values

In [48]:
x=x[:,1:]
y=y[:,1:].reshape((-1,))

In [49]:
y.shape #earlier if we haven't reshaped it's shape is (399, 1)

(399,)

In [50]:
x.shape

(399, 2)

### Training

In [52]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=12)

In [53]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [54]:
y_pred=knn.predict(X_test)

In [55]:
y_pred

array([1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1.,
       1., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 1., 0., 0.,
       1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0.])

In [58]:
y[40]==y_pred

array([False, False, False,  True,  True, False,  True,  True, False,
       False,  True,  True,  True, False, False, False, False, False,
       False,  True, False, False, False,  True, False, False, False,
        True, False,  True,  True,  True,  True, False, False, False,
        True, False, False,  True,  True, False, False,  True,  True,
        True, False,  True,  True, False, False, False, False, False,
       False, False,  True, False, False,  True,  True, False, False,
       False,  True, False,  True,  True, False,  True, False, False,
       False, False,  True,  True, False,  True,  True,  True])

In [59]:
knn.score(x,y) #read docs
#Return the mean accuracy on the given test data and labels.


1.0

In [ ]:
# KNN using Sklearn

In [60]:
from sklearn.neighbors import KNeighborsClassifier
#euclidean distance
knn1 =KNeighborsClassifier(n_neighbors=15,metric="minkowski",p=2)


In [66]:
Xtr, Xt, ytr, yt = train_test_split(x, y, test_size=0.2, random_state=12)

In [67]:
knn1.fit(Xtr,y)

KNeighborsClassifier(n_neighbors=15)

In [68]:
#predicted Classes of KNN Classifier
ypred=knn1.predict(Xt)
ypred[:5]

array([1., 1., 1., 0., 0.])

In [70]:
#Accuracy Score
from sklearn.metrics import accuracy_score
accuracy_score(yt,ypred)

1.0

In [72]:
#Get probabalities of predicted classes first is 0 and second is for 1
pred=knn1.predict_proba(Xt)
pred[:5]

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.]])