# Operators

## 1. Arithmetic operators
 
| Symbol | Task Performed |
|----|--------------------|
| +  | Addition |
| -  | Subtraction |
| /  | division |
| %  | mod |
| *  | multiplication |
| //  | floor division |
| **  | to the power of |

In [1]:
print(2 + 5)
print(5 - 2)
print(10 / 2) # gives float value
print(110 % 100) # remainder 
print(5*2)
print(10 // 2) # floor division 
print(2**5)   # a^b

7
3
5.0
10
10
5
32


## 2. Comparison operators

   | Symbol | Task Performed |
   |----|---|
   | == | True, if it is equal |
   | !=  | True, if not equal to |
   | < | less than |
   | > | greater than |
   | <=  | less than or equal to |
   | >=  | greater than or equal to |

In [2]:
print(2==2)
print(2!=2)
print(2<3)
print(2>2)
print(2<=3)
print(2>=3)

True
False
True
False
True
False


In [3]:
# we can also do String comparsion (lexographically)
print("abc" < "abd")
print("xy" < "abc")
print("ABC" < "abc") # here it see ASCII value
print(ord("A"))
print(ord("a"))


True
False
True
65
97


## 3. Assignment operators

- =
- +=
- -=
- *=
- /=
- %=
- //= &nbsp;     means x=x//4
- \**= &nbsp;    means x=x\**2
- &=   &nbsp;    means x=x & 2  &nbsp;  (and)
- |=  &nbsp;     means x=x|2  &nbsp;     (or)
- ^=
- \>>=  &nbsp;   both of these are shift op.(bitwise operators)
- <<=

## 4. Logical Operators

   | Symbol | Task Performed |
   |----|---|
   | and | True if both statements are true |
   | or  | True if one of the statements is true |
   | not | opposite of the result(reverse the result) |
   

In [5]:
isinstance(1,int)

True

In [6]:
isinstance(1.0,float)

True

In [7]:
print(isinstance(True,bool))
print(isinstance(True,int))
print(5 + True) #True is nothingbut is integer (inherted from integers)
print(5 + bool(1))
print(type(True))

True
True
6
6
<class 'bool'>


In [8]:
print(True and True)
print(not True) #hence similarly you can print truth table    

True
False


In [9]:
#truthy value - +int,-int, " ", True
#falsy value  - 0, "", False
5 and 0

# and can be represented as &&
# or can be represented as ||


0

a truthy value is a value that is considered true when encountered in a Boolean context. All values are truthy unless they are defined as falsy (i.e., except for false , 0 , -0 , 0n , "" , null , undefined , and NaN ).

#### Short Circuiting 

0 || B = B <br>
1 || B = 1 <br>
0 && B = 0 <br>
1 && B = B <br>

In [11]:
" " and "aryan" #true and true gives us true
0 and 1


0

## 5. Bitwise Operators
| Symbol | Task Performed |
|----|---|
| & | Sets each bit to 1 if both bits are 1  |
| \| | Sets each bit to 1 if one of two bits is 1  |
| ^ |  Sets each bit to 1 if only one of two bits is 1  |
| ~ |   Inverts all the bits |
| >> | Shift left by pushing zeros in from the right and let the leftmost bits fall off   |
| << |  Shift right by pushing copies of the leftmost bit in from the left, and let the rightmost bits fall off  |


## 6. Identity and Membership Operators

| Symbol | Task Performed |
   |----|---|
   |**Identity**|   |
   | is | True if both variables are the same object |
   | is not  | True if both variables are not the same object |
   | **Membership**|   |
   | in | True if a sequence with the specified value is present in the object |
   | not in | True if a sequence with the specified value is not present in the object |

In [12]:
ord("A")

65

In [13]:

(2>7) and (5>7) 
#to fullfill "and" operaator
#all the coditions should be true

False

In [14]:
(7>=7 ) or (7>10)

True

In [15]:
not True


False

In [16]:
not( 3>5)

True

In [17]:
10 & 4

0

In [18]:
10|4

14

In [19]:
bin(10)

'0b1010'

In [20]:
0b1010

10

## Numpy logical operators

The Python Numpy logical operators and logical functions are to compute truth value using the Truth table, i.,e Boolean True or false. Python numpy logical functions are logical_and, logical_or, logical_not, and logical_xor. Like any other programming, numpy has regular logical operators like and, or, not and xor.

In [2]:
# Create arrays
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

# my_house greater than 18.5 or smaller than 10
print(np.logical_or(my_house > 18.5 , my_house < 10))

# Both my_house and your_house smaller than 11
print( np.logical_and(my_house <11, your_house<11 ))

[False  True False  True]
[False False False  True]


In [3]:
x = np.array([5, 0, 8, 2, 22, 7, 4, 11, 9, 1, 6])
print(x)
print('---logical_not result  of an array---\n', np.logical_not(x > 8))
print()
 
y = np.random.randn(3, 4)
print(y)
print('\n---logical_not result of Two Dimensional Array--- \n',
      np.logical_not(y > 1))
print()
 
z = np.random.randint(1, 20, size = (2, 3, 5))
print(z)
print('\n---logical_not result of Three Dimensional Array---\n',
      np.logical_not(z < 10))


[ 5  0  8  2 22  7  4 11  9  1  6]
---logical_not result  of an array---
 [ True  True  True  True False  True  True False False  True  True]

[[ 0.8154415  -0.58678741  0.8880703  -0.31699306]
 [ 1.30808007 -0.70791222  1.58799425 -0.42626683]
 [-1.41821407 -0.32718429  0.20253031 -0.9241459 ]]

---logical_not result of Two Dimensional Array--- 
 [[ True  True  True  True]
 [False  True False  True]
 [ True  True  True  True]]

[[[11  1 11  1  5]
  [ 3  7 13 16  7]
  [ 1  9  8 17  7]]

 [[12 14 15 11 10]
  [14 15 16  7 11]
  [ 8 18 16  3 16]]]

---logical_not result of Three Dimensional Array---
 [[[ True False  True False False]
  [False False  True  True False]
  [False False False  True False]]

 [[ True  True  True  True  True]
  [ True  True  True False  True]
  [False  True  True False  True]]]


Reference For Numpy Logical Operator

[Reference1](https://www.tutorialgateway.org/python-numpy-logical-operators/#:~:text=The%20Python%20Numpy%20logical%20operators,%2C%20or%2C%20not%20and%20xor.)

[Reference2](https://www.geeksforgeeks.org/numpy-logical_and-python/)