In [1]:
import os
import numpy as np
import cv2

In [2]:
dataset_path = "./data/" #dataset folder


In [3]:
os.listdir(dataset_path)#operating system tell me list directory that the given path have it!!

['aryan.npy', 'aryan2.npy', 'robert.npy']

In [4]:
for fx in os.listdir(dataset_path):#operating system tellme list directory endswith .npy 
    if fx.endswith(".npy"):
        print(fx)
        
        

aryan.npy
aryan2.npy
robert.npy


In [5]:
face_data = []
labels = [] #y values in kNN


In [6]:
for fx in os.listdir(dataset_path):#operating system tellme list directory
    if fx.endswith(".npy"):
        l = fx.split(".")[0] #split by . and taking 0th part
        print(l)
#         np.load()

aryan
aryan2
robert


In [7]:
for fx in os.listdir(dataset_path):#operating system tellme list directory
    if fx.endswith(".npy"):
        l = fx.split(".")[0] #split by . and taking 0th part-->Name
        
        face_item=np.load(dataset_path+ fx) #storing imgs in numpy format --> Images
        print(face_item.shape)
        print(face_item)
        print(l)
        #break #here is for running one time
        face_data.append(face_item)
        #labels.append(l) here we not have to do this we have to append it 64 times
        # appending labels #times => faces
        for i in range(face_item.shape[0]):
            labels.append(l)
    break

(5, 30000)
[[232 222 218 ... 191 166 124]
 [231 223 218 ... 188 167 127]
 [253 253 255 ... 204 180 136]
 [255 254 255 ...  84 111 147]
 [253 253 255 ...  78 108 145]]
aryan


In [8]:
face_data

[array([[232, 222, 218, ..., 191, 166, 124],
        [231, 223, 218, ..., 188, 167, 127],
        [253, 253, 255, ..., 204, 180, 136],
        [255, 254, 255, ...,  84, 111, 147],
        [253, 253, 255, ...,  78, 108, 145]], dtype=uint8)]

In [9]:
face_data[0].shape

(5, 30000)

In [10]:
face_data[1].shape

IndexError: list index out of range

In [36]:
labels

['aryan', 'aryan', 'aryan', 'aryan', 'aryan']

In [37]:
import os
import numpy as np
import cv2

dataset_path = "./data1/"

face_data = []
labels = []

for fx in os.listdir(dataset_path):
    if fx.endswith(".npy"):
        l = fx.split(".")[0]
        
        face_item = np.load(dataset_path + fx)
        print(face_item.shape)
        print(l)
        
        face_data.append(face_item)
        # appending labels #times => faces
        for i in range(face_item.shape[0]):
            labels.append(l)


X = np.concatenate(face_data, axis =0)
y = np.array(labels)

FileNotFoundError: [WinError 3] The system cannot find the path specified: './data1/'

In [38]:
labels


[]

In [14]:
face_data[1].shape

IndexError: list index out of range

In [15]:
face_data[0].shape

IndexError: list index out of range

In [16]:
585+276

861

In [17]:
face_data #we have concat data from nparray to x
#according  axis=0

[]

In [18]:
#below we are concaticating the no. of images

In [19]:
X = np.concatenate(face_data, axis =0) 

#axis=0 is index row
#axis =1 is col

ValueError: need at least one array to concatenate

In [20]:
X

NameError: name 'X' is not defined

In [21]:
X.shape

NameError: name 'X' is not defined

In [22]:
y=np.array(labels)

In [23]:
y

array([], dtype=float64)

In [24]:
y.shape

(0,)

In [25]:
cv2.putText()

TypeError: putText() missing required argument 'img' (pos 1)