In [2]:
# Write a Python Script that captures images from your webcam video stream
# Extracts all Faces from the image frame (using haarcascades)
# Stores the Face information into numpy arrays


In [3]:
# 1. Read and show video stream, capture images
# 2. Detect Faces and show bounding box (haarcascade) on instant face 
# 3. Flatten the largest face image(gray scale) and save in a numpy array
# 4. Repeat the above for multiple people to generate training data

In [ ]:
import cv2
import numpy as np

cam = cv2.VideoCapture(0)
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_alt.xml")


In [7]:
skip = 0

while True:
    ret,frame = cam.read()
    if ret==False:
        continue
        
    cv2.imshow("Frame",frame)
    
    
    faces = face_cascade.detectMultiScale(frame,1.3,5)
    print(faces)
    
    
    
    #store every 10th faces
    if skip%10==0:
        #store the 10 face later on 
        pass
    
    
    
    key_pressed = cv2.waitKey(1) & 0xFF
    if key_pressed == ord('q'):
        break
cam.release()
cv2.destroyAllWindows()


()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[[246 175 158 158]]
[[250 177 152 152]]
[[256 182 142 142]]
[[253 181 144 144]]
[[260 184 142 142]]
[[259 180 146 146]]
[[266 185 138 138]]
[[263 185 139 139]]
[[261 182 144 144]]
[[268 185 140 140]]
()
[[258 171 163 163]]
[[266 177 150 150]]
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[[284 166 163 163]]
[[283 167 163 163]]
()
()
()
()
[[276 166 163 163]]
[[272 163 163 163]]
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()

In [8]:
for face in faces[-1:]:
    x,y,w,h = face
    cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,255),2)

In [ ]:
skip = 0

while True:
    ret,frame = cam.read()
    if ret==False:
        continue
        
    cv2.imshow("Frame",frame)
    
    
    faces = face_cascade.detectMultiScale(frame,1.3,5)
    print(faces)
    
    #make a rectangle box around faces
    for face in faces[-1:]:
        x,y,w,h = face
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,255),2)
    
    
    cv2.imshow("Frame",frame)
    
    
    
    #store every 10th faces
    if skip%10==0:
        #store the 10 face later on 
        pass
    
    
    
    key_pressed = cv2.waitKey(1) & 0xFF
    if key_pressed == ord('q'):
        break
cam.release()
cv2.destroyAllWindows()


In [ ]:
skip = 0
face_data = []
#store data in array of img in data folder 
dataset_path = './data/' 

while True:
    ret,frame = cam.read()
    if ret==False:
        continue
        
    cv2.imshow("Frame",frame)
    
    
    faces = face_cascade.detectMultiScale(frame,1.3,5)
    print(faces)
    
    #make a rectangle box around faces
    for face in faces[-1:]:
        x,y,w,h = face
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,255),2)
    
    
    cv2.imshow("Frame",frame)
    
    
    
    #store every 10th faces
    if skip%10==0:
        #store the 10 face later on 
        pass
    
    
    
    key_pressed = cv2.waitKey(1) & 0xFF
    if key_pressed == ord('q'):
        break
cam.release()
cv2.destroyAllWindows()
