In [38]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [39]:
df=pd.read_csv("mushrooms.csv")

In [40]:
df.head(10)

type cap_shape cap_surface cap_color bruises odor gill_attachment  \
0    p         x           s         n       t    p               f   
1    e         x           s         y       t    a               f   
2    e         b           s         w       t    l               f   
3    p         x           y         w       t    p               f   
4    e         x           s         g       f    n               f   
5    e         x           y         y       t    a               f   
6    e         b           s         w       t    a               f   
7    e         b           y         w       t    l               f   
8    p         x           y         w       t    p               f   
9    e         b           s         y       t    a               f   

  gill_spacing gill_size gill_color  ... stalk_surface_below_ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   
5            c         b          n  ...                        s   
6            c         b          g  ...                        s   
7            c         b          n  ...                        s   
8            c         n          p  ...                        s   
9            c         b          g  ...                        s   

  stalk_color_above_ring stalk_color_below_ring veil_type veil_color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   
5                      w                      w         p          w   
6                      w                      w         p          w   
7                      w                      w         p          w   
8                      w                      w         p          w   
9                      w                      w         p          w   

  ring_number ring_type spore_print_color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  
5           o         p                 k          n       g  
6           o         p                 k          n       m  
7           o         p                 n          s       m  
8           o         p                 k          v       g  
9           o         p                 k          s       m  

[10 rows x 23 columns]

In [41]:
df.shape

(8124, 23)

In [42]:
#type has p is for poisonous and n is for not
#so we have catogerical data 
#so to convert catogoriacl data into number
#we use label encoder in sklearn

### Encode Categorical data into numbers

In [43]:
le = LabelEncoder()
#le is 'LabelEncoder' object

In [44]:
a =np.array(["f","m","f","f","m"])

In [45]:
le.fit_transform(a)

array([0, 1, 0, 0, 1], dtype=int64)

In [46]:
le.classes_
#see mapping function

array(['f', 'm'], dtype='<U1')

In [47]:
le.inverse_transform([0])

array(['f'], dtype='<U1')

In [48]:
le.inverse_transform([1])

array(['m'], dtype='<U1')

In [49]:
#see mapping see its dict

In [50]:
df = df.apply(le.fit_transform)
#u can also first fit then transform

In [51]:
#apply function apply in all series

In [52]:
df.head()

type  cap_shape  cap_surface  cap_color  bruises  odor  gill_attachment  \
0     1          5            2          4        1     6                1   
1     0          5            2          9        1     0                1   
2     0          0            2          8        1     3                1   
3     1          5            3          8        1     6                1   
4     0          5            2          3        0     5                1   

   gill_spacing  gill_size  gill_color  ...  stalk_surface_below_ring  \
0             0          1           4  ...                         2   
1             0          0           4  ...                         2   
2             0          0           5  ...                         2   
3             0          1           5  ...                         2   
4             1          0           4  ...                         2   

   stalk_color_above_ring  stalk_color_below_ring  veil_type  veil_color  \
0                       7                       7          0           2   
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   

   ring_number  ring_type  spore_print_color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  

[5 rows x 23 columns]

In [53]:
data=df.values

In [54]:
data[0,:]

array([1, 5, 2, 4, 1, 6, 1, 0, 1, 4, 0, 3, 2, 2, 7, 7, 0, 2, 1, 4, 2, 3,
       5])

In [55]:
data[0]
#here categorical data can too work but 
#in most of the case we have to convert categorical data into numbers

array([1, 5, 2, 4, 1, 6, 1, 0, 1, 4, 0, 3, 2, 2, 7, 7, 0, 2, 1, 4, 2, 3,
       5])

In [56]:
data[:,0]

array([1, 0, 0, ..., 0, 1, 0])

In [57]:
X=data[:,1:] #we have to give data
y=data[:,0] #and predict output

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [59]:
np.unique(y)

array([0, 1])

In [60]:
np.unique(y_train)

array([0, 1])

In [61]:
np.unique(y_test)

array([0, 1])

In [63]:
np.unique(X_train)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Classifier

In [64]:
def prior_prob(y_train, label):
    total_examples = y_train.shape[0] #total example of all classes
    classes_examples = np.sum(y_train == label) #taking sum of all the prob of specific class
    
    return (classes_examples)/float(total_examples)

In [66]:
prior_prob(y_train,1)

0.48222803508232037

In [67]:
prior_prob(y_train,0)

0.5177719649176796

In [69]:
a = np.array([1, 0,0,0,0,1,1,0,0,0 ])
prior_prob(a, 0)

0.7