In [38]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [39]:
df=pd.read_csv("mushrooms.csv")

In [40]:
df.head(10)

type cap_shape cap_surface cap_color bruises odor gill_attachment  \
0    p         x           s         n       t    p               f   
1    e         x           s         y       t    a               f   
2    e         b           s         w       t    l               f   
3    p         x           y         w       t    p               f   
4    e         x           s         g       f    n               f   
5    e         x           y         y       t    a               f   
6    e         b           s         w       t    a               f   
7    e         b           y         w       t    l               f   
8    p         x           y         w       t    p               f   
9    e         b           s         y       t    a               f   

  gill_spacing gill_size gill_color  ... stalk_surface_below_ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   
5            c         b          n  ...                        s   
6            c         b          g  ...                        s   
7            c         b          n  ...                        s   
8            c         n          p  ...                        s   
9            c         b          g  ...                        s   

  stalk_color_above_ring stalk_color_below_ring veil_type veil_color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   
5                      w                      w         p          w   
6                      w                      w         p          w   
7                      w                      w         p          w   
8                      w                      w         p          w   
9                      w                      w         p          w   

  ring_number ring_type spore_print_color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  
5           o         p                 k          n       g  
6           o         p                 k          n       m  
7           o         p                 n          s       m  
8           o         p                 k          v       g  
9           o         p                 k          s       m  

[10 rows x 23 columns]

In [41]:
df.shape

(8124, 23)

In [42]:
#type has p is for poisonous and n is for not
#so we have catogerical data 
#so to convert catogoriacl data into number
#we use label encoder in sklearn

### Encode Categorical data into numbers

In [43]:
le = LabelEncoder()
#le is 'LabelEncoder' object

In [44]:
a =np.array(["f","m","f","f","m"])

In [45]:
le.fit_transform(a)

array([0, 1, 0, 0, 1], dtype=int64)

In [46]:
le.classes_
#see mapping function

array(['f', 'm'], dtype='<U1')

In [47]:
le.inverse_transform([0])

array(['f'], dtype='<U1')

In [48]:
le.inverse_transform([1])

array(['m'], dtype='<U1')

In [49]:
#see mapping see its dict

In [50]:
df = df.apply(le.fit_transform)
#u can also first fit then transform

In [51]:
#apply function apply in all series

In [52]:
df.head()

type  cap_shape  cap_surface  cap_color  bruises  odor  gill_attachment  \
0     1          5            2          4        1     6                1   
1     0          5            2          9        1     0                1   
2     0          0            2          8        1     3                1   
3     1          5            3          8        1     6                1   
4     0          5            2          3        0     5                1   

   gill_spacing  gill_size  gill_color  ...  stalk_surface_below_ring  \
0             0          1           4  ...                         2   
1             0          0           4  ...                         2   
2             0          0           5  ...                         2   
3             0          1           5  ...                         2   
4             1          0           4  ...                         2   

   stalk_color_above_ring  stalk_color_below_ring  veil_type  veil_color  \
0                       7                       7          0           2   
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   

   ring_number  ring_type  spore_print_color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  

[5 rows x 23 columns]

In [53]:
data=df.values

In [54]:
data[0,:]

array([1, 5, 2, 4, 1, 6, 1, 0, 1, 4, 0, 3, 2, 2, 7, 7, 0, 2, 1, 4, 2, 3,
       5])

In [55]:
data[0]
#here categorical data can too work but 
#in most of the case we have to convert categorical data into numbers

array([1, 5, 2, 4, 1, 6, 1, 0, 1, 4, 0, 3, 2, 2, 7, 7, 0, 2, 1, 4, 2, 3,
       5])

In [56]:
data[:,0]

array([1, 0, 0, ..., 0, 1, 0])

In [57]:
X=data[:,1:] #we have to give data
y=data[:,0] #and predict output

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [59]:
np.unique(y)

array([0, 1])

In [60]:
np.unique(y_train)

array([0, 1])

In [61]:
np.unique(y_test)

array([0, 1])

In [63]:
np.unique(X_train)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [76]:
 X_train.shape[1]
    #no of features

22

# Classifier

In [64]:
def prior_prob(y_train, label):
    total_examples = y_train.shape[0] #total example of all classes
    classes_examples = np.sum(y_train == label) #taking sum of all the prob of specific class
    
    return (classes_examples)/float(total_examples)

In [66]:
prior_prob(y_train,1)

0.48222803508232037

In [67]:
prior_prob(y_train,0)

0.5177719649176796

In [69]:
a = np.array([1, 0,0,0,0,1,1,0,0,0 ])
prior_prob(a, 0)

0.7

In [70]:
def cond_prob(X_train, y_train, feature_col, feature_val, label):
    X_filtered = X_train[y_train==label] #taking value of X_train that have y_train =label
    
    
    numerator = np.sum(X_filtered[:, feature_col] == feature_val)
    denom = np.sum(y_train==label)
    
    return numerator/float(denom)

# Compute : Likelihood and Posterior Probability

In [71]:
def predict(X_train, y_train, x_query):
    "x_query is a single testing point having n features"

    classes = np.unique(y_train)
    n_features = X_train.shape[1]
    post_prob = []
    #in this we are calculating posterior of differnt 
    #classes and appending it in list and find max prob of y_train by argmax()
    #return max class val 
    
    for label in classes:
        likelihood = 1.0
        # likelihood
        for f in range(n_features):
            cond = cond_prob(X_train, y_train, f, x_query[f], label)#xquery mrin is feature par jo val hai
            likelihood = likelihood*cond
            
        
        # prior
        prior = prior_prob(y_train, label)
        post = likelihood*prior
        
        post_prob.append(post)
        
    pred = np.argmax(post_prob)
    return pred

In [72]:
X_test[90]

array([ 2,  2,  4,  0,  5,  0,  0,  0, 11,  0,  0,  2,  2,  5,  5,  0,  1,
        1,  4,  8,  4,  2])

In [77]:
predict(X_train, y_train, X_test[79])
# 1 means not edible 
#0 means edible                                      

1

In [78]:
y_test[79]


1

In [87]:
X_test.shape


(1625, 22)

In [83]:
X_test.shape[0]
#total no. of example

1625

In [81]:
def accuracy(X_train, y_train, X_test, y_test):
    y_pred = []
    
    for i in range(X_test.shape[0]):
        pred_label = predict(X_train, y_train, X_test[i])
        y_pred.append(pred_label)
        
    y_pred = np.array(y_pred)
    
    acc = np.sum(y_pred == y_test)/ y_test.shape[0]
    
    return acc

In [88]:
accuracy(X_train, y_train, X_test, y_test)
#it do everything at test time
#at huge time at 1 million test point

0.9963076923076923

# Gaussian Naive Bayes

In [90]:
from sklearn.datasets import load_iris 
iris = load_iris()


In [91]:
X = iris.data
y = iris.target

In [99]:
X


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [100]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [92]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=1)


In [101]:
from sklearn.naive_bayes import GaussianNB
#three type of naive base
#GaussianNB,MultinomialNB,BernoulliNB

In [102]:
gnb = GaussianNB()


In [103]:
gnb.fit(X_train, y_train)


GaussianNB(priors=None, var_smoothing=1e-09)

In [104]:
gnb.predict(X_test)


array([0, 1, 1, 0, 2, 2, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0, 1, 2, 2, 0, 1, 2,
       1, 2, 0, 0, 0, 1, 0, 0, 2, 2, 2, 2, 2, 1, 2, 1])

In [105]:
gnb.score(X_test, y_test)


0.95

In [98]:
X_test[0]


array([5.8, 4. , 1.2, 0.2])

In [106]:
#https://www.geeksforgeeks.org/naive-bayes-classifiers/

# MNIST DATA

In [108]:
from sklearn.datasets import load_digits


In [109]:
digit = load_digits()


In [110]:
X = digit.data
y = digit.target

In [111]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=1)


In [112]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB


In [113]:
mnb = MultinomialNB()
bnb = BernoulliNB()
gnb = GaussianNB()

In [114]:
mnb.fit(X_train, y_train)
gnb.fit(X_train, y_train)
bnb.fit(X_train, y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [115]:
mnb.score(X_test, y_test)

0.8970792767732962

In [116]:
bnb.score(X_test, y_test)


0.8567454798331016

In [117]:
gnb.score(X_test, y_test)


0.8303198887343533

In [118]:
#naive bayes core
#https://nlp.stanford.edu/IR-book/html/htmledition/naive-bayes-text-classification-1.html