In [1]:
import os
import numpy as np
import cv2

In [2]:
dataset_path = "./data1/" #dataset folder


In [3]:
os.listdir(dataset_path)#operating system tell me list directory that the given path have it!!

['ARYAN.npy', 'robert.npy']

In [4]:
for fx in os.listdir(dataset_path):#operating system tellme list directory endswith .npy 
    if fx.endswith(".npy"):
        print(fx)
        
        

ARYAN.npy
robert.npy


In [5]:
face_data = []
labels = [] #y values in kNN


In [6]:
for fx in os.listdir(dataset_path):#operating system tellme list directory
    if fx.endswith(".npy"):
        l = fx.split(".")[0] #split by . and taking 0th part
        print(l)
#         np.load()

ARYAN
robert


In [11]:
for fx in os.listdir(dataset_path):#operating system tellme list directory
    if fx.endswith(".npy"):
        l = fx.split(".")[0] #split by . and taking 0th part-->Name
        
        face_item=np.load(dataset_path+ fx) #storing imgs in numpy format --> Images
        print(face_item.shape)
        print(face_item)
        print(l)
        #break #here is for running one time
        face_data.append(face_item)
        #labels.append(l) here we not have to do this we have to append it 64 times
        # appending labels #times => faces
        for i in range(face_item.shape[0]):
            labels.append(l)
    break

(276, 30000)
[[21 12 17 ... 41 38 30]
 [47 61 63 ... 13 16 20]
 [47 61 63 ... 13 16 20]
 ...
 [25 16 23 ... 52 48 36]
 [22 14 15 ... 48 43 35]
 [22 14 15 ... 48 43 35]]
ARYAN


In [12]:
face_data

[array([[21, 12, 17, ..., 41, 38, 30],
        [47, 61, 63, ..., 13, 16, 20],
        [47, 61, 63, ..., 13, 16, 20],
        ...,
        [25, 16, 23, ..., 52, 48, 36],
        [22, 14, 15, ..., 48, 43, 35],
        [22, 14, 15, ..., 48, 43, 35]], dtype=uint8),
 array([[21, 12, 17, ..., 41, 38, 30],
        [47, 61, 63, ..., 13, 16, 20],
        [47, 61, 63, ..., 13, 16, 20],
        ...,
        [25, 16, 23, ..., 52, 48, 36],
        [22, 14, 15, ..., 48, 43, 35],
        [22, 14, 15, ..., 48, 43, 35]], dtype=uint8)]

In [13]:
face_data[0].shape

(276, 30000)

In [14]:
face_data[1].shape

(276, 30000)

In [15]:
labels

['ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',


In [16]:
import os
import numpy as np
import cv2

dataset_path = "./data1/"

face_data = []
labels = []

for fx in os.listdir(dataset_path):
    if fx.endswith(".npy"):
        l = fx.split(".")[0]
        
        face_item = np.load(dataset_path + fx)
        print(face_item.shape)
        print(l)
        
        face_data.append(face_item)
        # appending labels #times => faces
        for i in range(face_item.shape[0]):
            labels.append(l)


X = np.concatenate(face_data, axis =0)
y = np.array(labels)

(276, 30000)
ARYAN
(585, 30000)
robert


In [17]:
labels


['ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',
 'ARYAN',


In [18]:
face_data[1].shape

(585, 30000)

In [19]:
face_data[0].shape

(276, 30000)

In [20]:
585+276

861

In [21]:
face_data #we have concat data from nparray to x
#according  axis=0

[array([[21, 12, 17, ..., 41, 38, 30],
        [47, 61, 63, ..., 13, 16, 20],
        [47, 61, 63, ..., 13, 16, 20],
        ...,
        [25, 16, 23, ..., 52, 48, 36],
        [22, 14, 15, ..., 48, 43, 35],
        [22, 14, 15, ..., 48, 43, 35]], dtype=uint8),
 array([[255, 254, 254, ...,  36,  11,  17],
        [255, 255, 253, ...,  49,  24,  22],
        [255, 255, 250, ...,  28,  13,   8],
        ...,
        [254, 240, 244, ..., 189, 159, 142],
        [255, 247, 248, ...,  37,  24,  22],
        [255, 244, 244, ...,  81,  62,  53]], dtype=uint8)]

In [22]:
#below we are concaticating the no. of images

In [23]:
X = np.concatenate(face_data, axis =0) 

#axis=0 is index row
#axis =1 is col

In [24]:
X

array([[ 21,  12,  17, ...,  41,  38,  30],
       [ 47,  61,  63, ...,  13,  16,  20],
       [ 47,  61,  63, ...,  13,  16,  20],
       ...,
       [254, 240, 244, ..., 189, 159, 142],
       [255, 247, 248, ...,  37,  24,  22],
       [255, 244, 244, ...,  81,  62,  53]], dtype=uint8)

In [25]:
X.shape

(861, 30000)

In [26]:
y=np.array(labels)

In [27]:
y

array(['ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN',
       'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN',
       'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN',
       'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN',
       'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN',
       'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN',
       'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN',
       'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN',
       'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN',
       'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN',
       'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN',
       'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN',
       'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN',
       'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN', 'ARYAN',
       'ARYAN', 'ARY

In [28]:
y.shape

(861,)

In [29]:
cv2.putText()

TypeError: putText() missing required argument 'img' (pos 1)