In [1]:
#nltk.org
!pip install nltk


# Get DATA 

In [8]:
import nltk
import numpy as np

In [3]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [4]:
from nltk.corpus import brown

In [6]:
print(brown.categories())
# from this i will extract the news category

['adventure', 'belles_lettres', 'editorial', 'fiction', 'government', 'hobbies', 'humor', 'learned', 'lore', 'mystery', 'news', 'religion', 'reviews', 'romance', 'science_fiction']


In [7]:
data=brown.sents(categories="news") #data is corpus and it has documents(sentences)  

In [9]:
brown.sents(categories="news") 

[['The', 'Fulton', 'County', 'Grand', 'Jury', 'said', 'Friday', 'an', 'investigation', 'of', "Atlanta's", 'recent', 'primary', 'election', 'produced', '``', 'no', 'evidence', "''", 'that', 'any', 'irregularities', 'took', 'place', '.'], ['The', 'jury', 'further', 'said', 'in', 'term-end', 'presentments', 'that', 'the', 'City', 'Executive', 'Committee', ',', 'which', 'had', 'over-all', 'charge', 'of', 'the', 'election', ',', '``', 'deserves', 'the', 'praise', 'and', 'thanks', 'of', 'the', 'City', 'of', 'Atlanta', "''", 'for', 'the', 'manner', 'in', 'which', 'the', 'election', 'was', 'conducted', '.'], ...]

In [10]:
len(data) #it has this len document and related with news

4623

In [11]:
data[0] # it is dicument


['The',
 'Fulton',
 'County',
 'Grand',
 'Jury',
 'said',
 'Friday',
 'an',
 'investigation',
 'of',
 "Atlanta's",
 'recent',
 'primary',
 'election',
 'produced',
 '``',
 'no',
 'evidence',
 "''",
 'that',
 'any',
 'irregularities',
 'took',
 'place',
 '.']

In [12]:
data[4622]

['This',
 'is',
 'one',
 'of',
 'the',
 'main',
 'reasons',
 'for',
 'National',
 'Library',
 'Week',
 ',',
 'April',
 '16-22',
 ',',
 'and',
 'for',
 'its',
 'theme',
 ':',
 '``',
 'For',
 'a',
 'richer',
 ',',
 'fuller',
 'life',
 ',',
 'read',
 "''",
 '!',
 '!']

In [15]:
" ".join(data[11])
#they are giving docs in break format we have just joined it 

"Implementation of Georgia's automobile title law was also recommended by the outgoing jury ."

In [16]:
brown.words(categories='news')
#it has lots of words in documents

['The', 'Fulton', 'County', 'Grand', 'Jury', 'said', ...]

In [21]:
news_words= brown.sents(categories='news')


In [22]:
len(news_words)


4623

# NLP pipeline
- Data Collection
- tokenization,stopword removal,stemming
- building vocabulary[BOW]
- vecorization of all docs
- perform classificarion

In [20]:
sen = "I love my country. I love to play cricket"


In [21]:
sen.split()


['I', 'love', 'my', 'country.', 'I', 'love', 'to', 'play', 'cricket']

In [6]:
from nltk.tokenize import sent_tokenize ,word_tokenize
#Data give in Doc also tokenize
#sent tokenize and word split by word and split by sent

In [9]:
nltk.download('punkt')


[nltk_data] Downloading package punkt to C:\Users\ARYAN
[nltk_data]     GULATI\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [10]:
document = """It was a very pleasant day. The weather was cool and there were light showers. 
I went to the market to buy some fruits."""

In [11]:
print(word_tokenize(document))


['It', 'was', 'a', 'very', 'pleasant', 'day', '.', 'The', 'weather', 'was', 'cool', 'and', 'there', 'were', 'light', 'showers', '.', 'I', 'went', 'to', 'the', 'market', 'to', 'buy', 'some', 'fruits', '.']


In [12]:
sent_tokenize(document)


['It was a very pleasant day.',
 'The weather was cool and there were light showers.',
 'I went to the market to buy some fruits.']

In [13]:
document.split(".")
#it include \n and so sent tokenize are avance version and have diff techinque

['It was a very pleasant day',
 ' The weather was cool and there were light showers',
 ' \nI went to the market to buy some fruits',
 '']

In [14]:
doc = "Mr. Modi is a good man. He is indian."


In [15]:
sent_tokenize(doc)


['Mr. Modi is a good man.', 'He is indian.']

In [16]:
word_tokenize(doc)

['Mr.', 'Modi', 'is', 'a', 'good', 'man', '.', 'He', 'is', 'indian', '.']

In [19]:
doc.split(".")


['Mr', ' Modi is a good man', ' He is indian', '']

In [22]:
from nltk.corpus import stopwords

In [25]:
nltk.download("stopwards")
#orwe can search in ntlk.download()

[nltk_data] Error loading stopwards: Package 'stopwards' not found in
[nltk_data]     index


False

In [29]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [27]:
l=stopwords.words('english')
#its just a list

In [28]:
'not' in l

True

In [30]:
l.remove("not")

In [31]:
'not' in l

False

In [32]:
stopwords.words()
#https://www.ranks.nl/stopwords

['إذ',
 'إذا',
 'إذما',
 'إذن',
 'أف',
 'أقل',
 'أكثر',
 'ألا',
 'إلا',
 'التي',
 'الذي',
 'الذين',
 'اللاتي',
 'اللائي',
 'اللتان',
 'اللتيا',
 'اللتين',
 'اللذان',
 'اللذين',
 'اللواتي',
 'إلى',
 'إليك',
 'إليكم',
 'إليكما',
 'إليكن',
 'أم',
 'أما',
 'أما',
 'إما',
 'أن',
 'إن',
 'إنا',
 'أنا',
 'أنت',
 'أنتم',
 'أنتما',
 'أنتن',
 'إنما',
 'إنه',
 'أنى',
 'أنى',
 'آه',
 'آها',
 'أو',
 'أولاء',
 'أولئك',
 'أوه',
 'آي',
 'أي',
 'أيها',
 'إي',
 'أين',
 'أين',
 'أينما',
 'إيه',
 'بخ',
 'بس',
 'بعد',
 'بعض',
 'بك',
 'بكم',
 'بكم',
 'بكما',
 'بكن',
 'بل',
 'بلى',
 'بما',
 'بماذا',
 'بمن',
 'بنا',
 'به',
 'بها',
 'بهم',
 'بهما',
 'بهن',
 'بي',
 'بين',
 'بيد',
 'تلك',
 'تلكم',
 'تلكما',
 'ته',
 'تي',
 'تين',
 'تينك',
 'ثم',
 'ثمة',
 'حاشا',
 'حبذا',
 'حتى',
 'حيث',
 'حيثما',
 'حين',
 'خلا',
 'دون',
 'ذا',
 'ذات',
 'ذاك',
 'ذان',
 'ذانك',
 'ذلك',
 'ذلكم',
 'ذلكما',
 'ذلكن',
 'ذه',
 'ذو',
 'ذوا',
 'ذواتا',
 'ذواتي',
 'ذي',
 'ذين',
 'ذينك',
 'ريث',
 'سوف',
 'سوى',
 'شتان',
 'عدا',
 'عسى',
 'عل'

In [54]:
'not' in sw

False

In [55]:
from nltk.tokenize import RegexpTokenizer

In [35]:
[w for w in word_tokenize(document.lower()) if w not in l] # list comprehension
#its just saying for  w in word document if w not in l then print w


['pleasant',
 'day',
 '.',
 'weather',
 'cool',
 'light',
 'showers',
 '.',
 'went',
 'market',
 'buy',
 'fruits',
 '.']

In [39]:
' '.join([w for w in word_tokenize(document) if w not in l]) # list comprehension


'It pleasant day . The weather cool light showers . I went market buy fruits .'

In [40]:
' '.join([w for w in word_tokenize(document.lower()) if w not in l]) # list comprehension
#we have use here lower function here 
#hence preventing overfitting
#so lower makes all words same

'pleasant day . weather cool light showers . went market buy fruits .'

In [41]:
from nltk.tokenize import RegexpTokenizer#this is class

In [42]:
#https://regex101.com/
#https://www.regexpal.com/
#https://www.rexegg.com/regex-quickstart.html
#https://www.rexegg.com/

In [43]:
my_regex_tokenizer = RegexpTokenizer(pattern="[a-z]+")
#like sent _token.. and word its like them 

In [44]:
abc = "Foxes love to make jumps. The quick brown fox 76989i7yy 876908 %^^%$&*** was seen jumping over the lovely dog from a 6ft feet,,  high wall...... mohituniyal@gmail.com"

In [45]:
abc

'Foxes love to make jumps. The quick brown fox 76989i7yy 876908 %^^%$&*** was seen jumping over the lovely dog from a 6ft feet,,  high wall...... mohituniyal@gmail.com'

In [46]:
" ".join(my_regex_tokenizer.tokenize(abc.lower()))


'foxes love to make jumps the quick brown fox i yy was seen jumping over the lovely dog from a ft feet high wall mohituniyal gmail com'

In [47]:
my_regex_tokenizer.tokenize(document.lower())

['it',
 'was',
 'a',
 'very',
 'pleasant',
 'day',
 'the',
 'weather',
 'was',
 'cool',
 'and',
 'there',
 'were',
 'light',
 'showers',
 'i',
 'went',
 'to',
 'the',
 'market',
 'to',
 'buy',
 'some',
 'fruits']

In [48]:
from nltk.stem import SnowballStemmer, PorterStemmer, LancasterStemmer
#these are different type of stemming

In [49]:
sb = SnowballStemmer(language='english')
#word that can be made from root 

In [50]:
sb.stem('lovely')


'love'

In [51]:
sb.stem("loved")


'love'

In [53]:
sb.stem("running")

'run'

In [54]:
sb.stem("ran")

'ran'

In [55]:
sb.stem('movie')


'movi'

In [59]:
sb.stem("microsoft")

'microsoft'

In [60]:
sb.stem("google")

'googl'

In [56]:
#idea is to reduce feature 


# BoW

In [58]:
# corpus is list of documents
corpus = [
        'Indian cricket team will wins World Cup, says Capt. Virat Kohli. World cup will be held at Sri Lanka.',
        'We will win next Lok Sabha Elections, says confident Indian PM',
        'Former Indian president APJ Abdul Kalam won the hearts of the people.',
        'The movie Raazi is an exciting Indian Spy thriller based upon a real story.'
]

In [61]:
#we have to iterate and see unique words 
from sklearn.feature_extraction.text import CountVectorizer


In [62]:
cv = CountVectorizer() #constructor
#cv is count vectorize  ka object

In [63]:
cv.fit_transform(corpus)
#it will do training and apply learning on corpus as well (apply on corpus -transform)

<4x45 sparse matrix of type '<class 'numpy.int64'>'
	with 51 stored elements in Compressed Sparse Row format>

In [71]:
vectorized_corpus = cv.fit_transform(corpus)
#vectorized_corpus its asparse matrix

In [66]:
vectorized_corpus
#(4,45) matrix 

<4x45 sparse matrix of type '<class 'numpy.int64'>'
	with 51 stored elements in Compressed Sparse Row format>

In [67]:
print(vectorized_corpus)


  (0, 15)	1
  (0, 8)	1
  (0, 34)	1
  (0, 40)	2
  (0, 42)	1
  (0, 44)	2
  (0, 9)	2
  (0, 30)	1
  (0, 6)	1
  (0, 38)	1
  (0, 18)	1
  (0, 5)	1
  (0, 14)	1
  (0, 3)	1
  (0, 32)	1
  (0, 19)	1
  (1, 15)	1
  (1, 40)	1
  (1, 30)	1
  (1, 39)	1
  (1, 41)	1
  (1, 22)	1
  (1, 20)	1
  (1, 29)	1
  (1, 10)	1
  :	:
  (1, 25)	1
  (2, 15)	1
  (2, 12)	1
  (2, 26)	1
  (2, 2)	1
  (2, 0)	1
  (2, 17)	1
  (2, 43)	1
  (2, 35)	2
  (2, 13)	1
  (2, 23)	1
  (2, 24)	1
  (3, 15)	1
  (3, 35)	1
  (3, 21)	1
  (3, 27)	1
  (3, 16)	1
  (3, 1)	1
  (3, 11)	1
  (3, 31)	1
  (3, 36)	1
  (3, 4)	1
  (3, 37)	1
  (3, 28)	1
  (3, 33)	1


In [68]:
vectorized_corpus.shape


(4, 45)

In [70]:
vectorized_corpus.toarray()

array([[0, 0, 0, 1, 0, 1, 1, 0, 1, 2, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 2, 0, 1, 0,
        2],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
        1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
        0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1,
        0],
       [0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
        0]], dtype=int64)

In [69]:
#to convert it into array or DENSE ARRAY
vc_dense = vectorized_corpus.toarray()
vc_dense[1]

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0], dtype=int64)

In [72]:
vectorized_corpus.nnz
#this function tell no of non zero elements

51

In [79]:
total=(vectorized_corpus.shape[0]*vectorized_corpus.shape[1])

In [80]:
sparsity=(vectorized_corpus.nnz)/total


In [82]:
sparsity #see once google it 

0.2833333333333333

In [84]:
cv.vocabulary_

{'indian': 15,
 'cricket': 8,
 'team': 34,
 'will': 40,
 'wins': 42,
 'world': 44,
 'cup': 9,
 'says': 30,
 'capt': 6,
 'virat': 38,
 'kohli': 18,
 'be': 5,
 'held': 14,
 'at': 3,
 'sri': 32,
 'lanka': 19,
 'we': 39,
 'win': 41,
 'next': 22,
 'lok': 20,
 'sabha': 29,
 'elections': 10,
 'confident': 7,
 'pm': 25,
 'former': 12,
 'president': 26,
 'apj': 2,
 'abdul': 0,
 'kalam': 17,
 'won': 43,
 'the': 35,
 'hearts': 13,
 'of': 23,
 'people': 24,
 'movie': 21,
 'raazi': 27,
 'is': 16,
 'an': 1,
 'exciting': 11,
 'spy': 31,
 'thriller': 36,
 'based': 4,
 'upon': 37,
 'real': 28,
 'story': 33}

In [83]:
len(cv.vocabulary_)

45

In [73]:
print(cv.vocabulary_)# so it has 45 entries
#dictonary which column is associated with word 

{'indian': 15, 'cricket': 8, 'team': 34, 'will': 40, 'wins': 42, 'world': 44, 'cup': 9, 'says': 30, 'capt': 6, 'virat': 38, 'kohli': 18, 'be': 5, 'held': 14, 'at': 3, 'sri': 32, 'lanka': 19, 'we': 39, 'win': 41, 'next': 22, 'lok': 20, 'sabha': 29, 'elections': 10, 'confident': 7, 'pm': 25, 'former': 12, 'president': 26, 'apj': 2, 'abdul': 0, 'kalam': 17, 'won': 43, 'the': 35, 'hearts': 13, 'of': 23, 'people': 24, 'movie': 21, 'raazi': 27, 'is': 16, 'an': 1, 'exciting': 11, 'spy': 31, 'thriller': 36, 'based': 4, 'upon': 37, 'real': 28, 'story': 33}


In [86]:
vc_dense[2]
#to tell the mapping of words to coresssponding column number 
#or to convert array into words 

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1,
       0], dtype=int64)

In [ ]:
cv.inverse_transform(vc_dense[2])
#ordder here doesnt mATTER

In [87]:
cv.get_feature_names()
#tell all features

['abdul',
 'an',
 'apj',
 'at',
 'based',
 'be',
 'capt',
 'confident',
 'cricket',
 'cup',
 'elections',
 'exciting',
 'former',
 'hearts',
 'held',
 'indian',
 'is',
 'kalam',
 'kohli',
 'lanka',
 'lok',
 'movie',
 'next',
 'of',
 'people',
 'pm',
 'president',
 'raazi',
 'real',
 'sabha',
 'says',
 'spy',
 'sri',
 'story',
 'team',
 'the',
 'thriller',
 'upon',
 'virat',
 'we',
 'will',
 'win',
 'wins',
 'won',
 'world']

In [90]:
my_text = ["my name is rorbot, Indian president is a good person."]

In [92]:
cv.transform(my_text).toarray()
#those words are in vocab at training time
#its recognise them only and put it
#to array by allocating  value to it 

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0]], dtype=int64)

# Other ways of creating features

In [96]:
cv = CountVectorizer(ngram_range=(1,2))

In [99]:
cv.fit_transform(corpus)
#so we can see features are increased

<4x95 sparse matrix of type '<class 'numpy.int64'>'
	with 101 stored elements in Compressed Sparse Row format>

In [100]:
cv.vocabulary_


{'indian': 31,
 'cricket': 16,
 'team': 69,
 'will': 83,
 'wins': 89,
 'world': 93,
 'cup': 18,
 'says': 61,
 'capt': 12,
 'virat': 79,
 'kohli': 40,
 'be': 10,
 'held': 29,
 'at': 6,
 'sri': 66,
 'lanka': 42,
 'indian cricket': 32,
 'cricket team': 17,
 'team will': 70,
 'will wins': 86,
 'wins world': 90,
 'world cup': 94,
 'cup says': 19,
 'says capt': 62,
 'capt virat': 13,
 'virat kohli': 80,
 'kohli world': 41,
 'cup will': 20,
 'will be': 84,
 'be held': 11,
 'held at': 30,
 'at sri': 7,
 'sri lanka': 67,
 'we': 81,
 'win': 87,
 'next': 47,
 'lok': 43,
 'sabha': 59,
 'elections': 21,
 'confident': 14,
 'pm': 52,
 'we will': 82,
 'will win': 85,
 'win next': 88,
 'next lok': 48,
 'lok sabha': 44,
 'sabha elections': 60,
 'elections says': 22,
 'says confident': 63,
 'confident indian': 15,
 'indian pm': 33,
 'former': 25,
 'president': 53,
 'apj': 4,
 'abdul': 0,
 'kalam': 38,
 'won': 91,
 'the': 71,
 'hearts': 27,
 'of': 49,
 'people': 51,
 'former indian': 26,
 'indian presiden

In [101]:
cv = CountVectorizer(ngram_range=(1,2), max_features=40)


In [102]:
cv.fit_transform(corpus)


<4x40 sparse matrix of type '<class 'numpy.int64'>'
	with 46 stored elements in Compressed Sparse Row format>

In [103]:
cv.vocabulary_


{'indian': 1,
 'team': 20,
 'will': 28,
 'wins': 34,
 'world': 38,
 'cup': 0,
 'says': 13,
 'virat': 24,
 'sri': 18,
 'will wins': 31,
 'wins world': 35,
 'world cup': 39,
 'says capt': 14,
 'virat kohli': 25,
 'will be': 29,
 'sri lanka': 19,
 'we': 26,
 'win': 32,
 'sabha': 11,
 'pm': 4,
 'we will': 27,
 'will win': 30,
 'win next': 33,
 'sabha elections': 12,
 'says confident': 15,
 'president': 5,
 'won': 36,
 'the': 21,
 'people': 3,
 'president apj': 6,
 'won the': 37,
 'of the': 2,
 'raazi': 7,
 'spy': 16,
 'real': 9,
 'raazi is': 8,
 'spy thriller': 17,
 'thriller based': 22,
 'upon real': 23,
 'real story': 10}

# TfIdf Normalisation

In [104]:
from sklearn.feature_extraction.text import TfidfVectorizer
#http://www.tfidf.com/

In [105]:
tfidf = TfidfVectorizer()


In [106]:
vc = tfidf.fit_transform(corpus)



In [109]:
vc.toarray()
#term frequency shown as its weighted so its more reliable

array([[0.        , 0.        , 0.        , 0.21138162, 0.        ,
        0.21138162, 0.21138162, 0.        , 0.21138162, 0.42276324,
        0.        , 0.        , 0.        , 0.        , 0.21138162,
        0.1103077 , 0.        , 0.        , 0.21138162, 0.21138162,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.1666557 , 0.        , 0.21138162, 0.        , 0.21138162,
        0.        , 0.        , 0.        , 0.21138162, 0.        ,
        0.3333114 , 0.        , 0.21138162, 0.        , 0.42276324],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.32417842, 0.        , 0.        ,
        0.32417842, 0.        , 0.        , 0.        , 0.        ,
        0.16916975, 0.        , 0.        , 0.        , 0.        ,
        0.32417842, 0.        , 0.32417842, 0.        , 0.        ,
        0.32417842, 0.        , 0.        , 0. 

In [107]:
print(vc)


  (0, 19)	0.21138162089799728
  (0, 32)	0.21138162089799728
  (0, 3)	0.21138162089799728
  (0, 14)	0.21138162089799728
  (0, 5)	0.21138162089799728
  (0, 18)	0.21138162089799728
  (0, 38)	0.21138162089799728
  (0, 6)	0.21138162089799728
  (0, 30)	0.1666556978718695
  (0, 9)	0.42276324179599456
  (0, 44)	0.42276324179599456
  (0, 42)	0.21138162089799728
  (0, 40)	0.333311395743739
  (0, 34)	0.21138162089799728
  (0, 8)	0.21138162089799728
  (0, 15)	0.11030769881732065
  (1, 25)	0.32417842259348545
  (1, 7)	0.32417842259348545
  (1, 10)	0.32417842259348545
  (1, 29)	0.32417842259348545
  (1, 20)	0.32417842259348545
  (1, 22)	0.32417842259348545
  (1, 41)	0.32417842259348545
  (1, 39)	0.32417842259348545
  (1, 30)	0.255585991926846
  :	:
  (1, 15)	0.16916974924594824
  (2, 24)	0.29162217443775823
  (2, 23)	0.29162217443775823
  (2, 13)	0.29162217443775823
  (2, 35)	0.4598365438714178
  (2, 43)	0.29162217443775823
  (2, 17)	0.29162217443775823
  (2, 0)	0.29162217443775823
  (2, 2)	0.291622

In [108]:
tfidf.vocabulary_


{'indian': 15,
 'cricket': 8,
 'team': 34,
 'will': 40,
 'wins': 42,
 'world': 44,
 'cup': 9,
 'says': 30,
 'capt': 6,
 'virat': 38,
 'kohli': 18,
 'be': 5,
 'held': 14,
 'at': 3,
 'sri': 32,
 'lanka': 19,
 'we': 39,
 'win': 41,
 'next': 22,
 'lok': 20,
 'sabha': 29,
 'elections': 10,
 'confident': 7,
 'pm': 25,
 'former': 12,
 'president': 26,
 'apj': 2,
 'abdul': 0,
 'kalam': 17,
 'won': 43,
 'the': 35,
 'hearts': 13,
 'of': 23,
 'people': 24,
 'movie': 21,
 'raazi': 27,
 'is': 16,
 'an': 1,
 'exciting': 11,
 'spy': 31,
 'thriller': 36,
 'based': 4,
 'upon': 37,
 'real': 28,
 'story': 33}