In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [3]:
iris=pd.read_csv("./IRIS.csv") #just reading csv file

In [4]:
iris.head()  #just getting what is our data is?

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [5]:
iris.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [6]:
X=iris.iloc[:,:4].values   #just getting reuired columns ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
y=iris["species"].values

In [8]:
y[y=='Iris-setosa']=0
y[y=='Iris-versicolor']=1
y[y=='Iris-virginica']=2

In [9]:
y=y.astype("int")
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X.shape

(150, 4)

In [12]:
y.shape

(150,)

In [13]:
dic={
    0:'Iris-setosa',
    1:'Iris-versicolor',
    2:'Iris-virginica'
}

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [15]:
def find_distance(pA, pB):
    return np.sum((pB - pA)**2)**0.5 

In [18]:
x_query= np.array([7.2, 3.6, 5.1, 2.5])
x_query.shape

(4,)

In [19]:
def kNN(X, y, x_query, k = 5): #here we can keep k as default parameter
    
    """
           shape    Datatype 
    X - > (150, 4)  np array
    y - > (150,) np array
    x_query -> (4,) np array
    k -> scaler  int
    
    do knn for classification
    """
    
    m = X.shape[0] #total no. of examples we have 
    distances = [] 
    for i in range(m):
        dis = find_distance(x_query, X[i]) #
        distances.append((dis,y[i])) #so here we are appending list of tuple
        
    distances = sorted(distances) #after sorting 
    distances = distances[:k] #we are taking first k elements
    
    distances = np.array(distances) #storing distances in array
    labels = distances[:, 1] #for extracting labels
    
    
    
    uniq_label, counts =np.unique(labels, return_counts=True) #it find unique elements and return count and label

    pred = uniq_label[counts.argmax()] #here we are finding max occureded label
    
    
    return dic[int(pred)] #here we are converting int to float 

In [20]:
kNN(X,y,x_query,k=9)

'Iris-virginica'

In [21]:
X_test.shape

(30, 4)

In [22]:

predictions = []
for i in range(30):
    p = kNN(X_train , y_train, X_test[i], k=9)
    
    predictions.append(p)

In [23]:
p

'Iris-setosa'

In [24]:
p=np.array(predictions)
p[p=='Iris-setosa']=0
p[p=='Iris-versicolor']=1
p[p=='Iris-virginica']=2

p = ','.join(p)
p = np.fromstring( p, dtype=np.int, sep=',' )
p

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [25]:

type(y_test)
y_test=y_test.astype("int")
y_test.dtype
y_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [26]:
arr=(y_test[:30] == p)

type(arr)

numpy.ndarray

In [27]:
(y_test[:30] == p).sum()/len(predictions)

1.0

In [28]:
from sklearn.neighbors import KNeighborsClassifier

In [29]:
knn = KNeighborsClassifier()

In [30]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [33]:
knn.predict([X_test[29]])

array([0])

In [34]:
y_test[29]

0